// Copyright (c) 2016, Open DICOMweb Project. All rights reserved.
// Use of this source code is governed by the open source license
// that can be found in the LICENSE file.
// Author: Jim Philbin <jfphilbin@gmail.edu> -
// See the AUTHORS file for other contributors.

// *** This file generated by '../deid/generate_basic_profile.dart' ***
// ----------------------------------------------------------

import 'package:core/dicom.dart';
import 'package:deid/src/deid/action.dart';

class BasicProfile {
  final int tag;
  final String keyword;
  final Action action;

  const BasicProfile(this.tag, this.keyword, this.action);

  static lookup(int tag) => map[tag];

    void deIdentify(Dataset ds) {
    for (int i = 0; i < tags.length; i++) {
    // TODO: fix
    //  Attribute a = ds.lookup(tags[i]);
      actions[i](ds, tags[i]);
    }
  }

  static const kAccessionNumber = const BasicProfile(0x00080050, "AccessionNumber", Action.Z);
  static const kAcquisitionComments = const BasicProfile(0x00184000, "AcquisitionComments", Action.X);
  static const kAcquisitionContextSequence = const BasicProfile(0x00400555, "AcquisitionContextSequence", Action.X);
  static const kAcquisitionDate = const BasicProfile(0x00080022, "AcquisitionDate", Action.XZ);
  static const kAcquisitionDateTime = const BasicProfile(0x0008002A, "AcquisitionDateTime", Action.XD);
  static const kAcquisitionDeviceProcessingDescription = const BasicProfile(0x00181400, "AcquisitionDeviceProcessingDescription", Action.XD);
  static const kAcquisitionProtocolDescription = const BasicProfile(0x00189424, "AcquisitionProtocolDescription", Action.X);
  static const kAcquisitionTime = const BasicProfile(0x00080032, "AcquisitionTime", Action.XZ);
  static const kActualHumanPerformersSequence = const BasicProfile(0x00404035, "ActualHumanPerformersSequence", Action.X);
  static const kAdditionalPatientsHistory = const BasicProfile(0x001021B0, "AdditionalPatientsHistory", Action.X);
  static const kAdmissionID = const BasicProfile(0x00380010, "AdmissionID", Action.X);
  static const kAdmittingDate = const BasicProfile(0x00380020, "AdmittingDate", Action.X);
  static const kAdmittingDiagnosesCodeSequence = const BasicProfile(0x00081084, "AdmittingDiagnosesCodeSequence", Action.X);
  static const kAdmittingDiagnosesDescription = const BasicProfile(0x00081080, "AdmittingDiagnosesDescription", Action.X);
  static const kAdmittingTime = const BasicProfile(0x00380021, "AdmittingTime", Action.X);
  static const kAffectedSOPInstanceUID = const BasicProfile(0x00001000, "AffectedSOPInstanceUID", Action.X);
  static const kAllergies = const BasicProfile(0x00102110, "Allergies", Action.X);
  static const kArbitrary = const BasicProfile(0x40000010, "Arbitrary", Action.X);
  static const kAuthorObserverSequence = const BasicProfile(0x0040A078, "AuthorObserverSequence", Action.X);
  static const kBranchofService = const BasicProfile(0x00101081, "BranchofService", Action.X);
  static const kCassetteID = const BasicProfile(0x00181007, "CassetteID", Action.X);
  static const kCommentsonthePerformedProcedureStep = const BasicProfile(0x00400280, "CommentsonthePerformedProcedureStep", Action.X);
  static const kConcatenationUID = const BasicProfile(0x00209161, "ConcatenationUID", Action.U);
  static const kConfidentialityConstraintonPatientDataDescription = const BasicProfile(0x00403001, "ConfidentialityConstraintonPatientDataDescription", Action.X);
  static const kContentCreatorsName = const BasicProfile(0x00700084, "ContentCreatorsName", Action.Z);
  static const kContentCreatorsIdentificationCodeSequence = const BasicProfile(0x00700086, "ContentCreatorsIdentificationCodeSequence", Action.X);
  static const kContentDate = const BasicProfile(0x00080023, "ContentDate", Action.ZD);
  static const kContentSequence = const BasicProfile(0x0040A730, "ContentSequence", Action.X);
  static const kContentTime = const BasicProfile(0x00080033, "ContentTime", Action.ZD);
  static const kContextGroupExtensionCreatorUID = const BasicProfile(0x0008010D, "ContextGroupExtensionCreatorUID", Action.U);
  static const kContrastBolusAgent = const BasicProfile(0x00180010, "ContrastBolusAgent", Action.ZD);
  static const kContributionDescription = const BasicProfile(0x0018A003, "ContributionDescription", Action.X);
  static const kCountryofResidence = const BasicProfile(0x00102150, "CountryofResidence", Action.X);
  static const kCreatorVersionUID = const BasicProfile(0x00089123, "CreatorVersionUID", Action.U);
  static const kCurrentPatientLocation = const BasicProfile(0x00380300, "CurrentPatientLocation", Action.X);
  static const kCurveDate = const BasicProfile(0x00080025, "CurveDate", Action.X);
  static const kCurveTime = const BasicProfile(0x00080035, "CurveTime", Action.X);
  static const kCustodialOrganizationSequence = const BasicProfile(0x0040A07C, "CustodialOrganizationSequence", Action.X);
  static const kDataSetTrailingPadding = const BasicProfile(0xFFFCFFFC, "DataSetTrailingPadding", Action.X);
  static const kDerivationDescription = const BasicProfile(0x00082111, "DerivationDescription", Action.X);
  static const kDetectorID = const BasicProfile(0x0018700A, "DetectorID", Action.XD);
  static const kDeviceSerialNumber = const BasicProfile(0x00181000, "DeviceSerialNumber", Action.XZD);
  static const kDeviceUID = const BasicProfile(0x00181002, "DeviceUID", Action.U);
  static const kDigitalSignatureUID = const BasicProfile(0x04000100, "DigitalSignatureUID", Action.X);
  static const kDigitalSignaturesSequence = const BasicProfile(0xFFFAFFFA, "DigitalSignaturesSequence", Action.X);
  static const kDimensionOrganizationUID = const BasicProfile(0x00209164, "DimensionOrganizationUID", Action.U);
  static const kDischargeDiagnosisDescription = const BasicProfile(0x00380040, "DischargeDiagnosisDescription", Action.X);
  static const kDistributionAddress = const BasicProfile(0x4008011A, "DistributionAddress", Action.X);
  static const kDistributionName = const BasicProfile(0x40080119, "DistributionName", Action.X);
  static const kDoseReferenceUID = const BasicProfile(0x300A0013, "DoseReferenceUID", Action.U);
  static const kEthnicGroup = const BasicProfile(0x00102160, "EthnicGroup", Action.X);
  static const kFailedSOPInstanceUIDList = const BasicProfile(0x00080058, "FailedSOPInstanceUIDList", Action.U);
  static const kFiducialUID = const BasicProfile(0x0070031A, "FiducialUID", Action.U);
  static const kFillerOrderNumber_ImagingServiceRequest = const BasicProfile(0x00402017, "FillerOrderNumber_ImagingServiceRequest", Action.Z);
  static const kFrameComments = const BasicProfile(0x00209158, "FrameComments", Action.X);
  static const kFrameofReferenceUID = const BasicProfile(0x00200052, "FrameofReferenceUID", Action.U);
  static const kGantryID = const BasicProfile(0x00181008, "GantryID", Action.X);
  static const kGeneratorID = const BasicProfile(0x00181005, "GeneratorID", Action.X);
  static const kGraphicAnnotationSequence = const BasicProfile(0x00700001, "GraphicAnnotationSequence", Action.D);
  static const kHumanPerformersName = const BasicProfile(0x00404037, "HumanPerformersName", Action.X);
  static const kHumanPerformersOrganization = const BasicProfile(0x00404036, "HumanPerformersOrganization", Action.X);
  static const kIconImageSequence0xseeNote12 = const BasicProfile(0x00880200, "IconImageSequence0xseeNote12", Action.X);
  static const kIdentifyingComments = const BasicProfile(0x00084000, "IdentifyingComments", Action.X);
  static const kImageComments = const BasicProfile(0x00204000, "ImageComments", Action.X);
  static const kImagePresentationComments = const BasicProfile(0x00284000, "ImagePresentationComments", Action.X);
  static const kImagingServiceRequestComments = const BasicProfile(0x00402400, "ImagingServiceRequestComments", Action.X);
  static const kImpressions = const BasicProfile(0x40080300, "Impressions", Action.X);
  static const kInstanceCreatorUID = const BasicProfile(0x00080014, "InstanceCreatorUID", Action.U);
  static const kInstitutionAddress = const BasicProfile(0x00080081, "InstitutionAddress", Action.X);
  static const kInstitutionCodeSequence = const BasicProfile(0x00080082, "InstitutionCodeSequence", Action.XZD);
  static const kInstitutionName = const BasicProfile(0x00080080, "InstitutionName", Action.XZD);
  static const kInstitutionalDepartmentName = const BasicProfile(0x00081040, "InstitutionalDepartmentName", Action.X);
  static const kInsurancePlanIdentification = const BasicProfile(0x00101050, "InsurancePlanIdentification", Action.X);
  static const kIntendedRecipientsofResultsIdentificationSequence = const BasicProfile(0x00401011, "IntendedRecipientsofResultsIdentificationSequence", Action.X);
  static const kInterpretationApproverSequence = const BasicProfile(0x40080111, "InterpretationApproverSequence", Action.X);
  static const kInterpretationAuthor = const BasicProfile(0x4008010C, "InterpretationAuthor", Action.X);
  static const kInterpretationDiagnosisDescription = const BasicProfile(0x40080115, "InterpretationDiagnosisDescription", Action.X);
  static const kInterpretationIDIssuer = const BasicProfile(0x40080202, "InterpretationIDIssuer", Action.X);
  static const kInterpretationRecorder = const BasicProfile(0x40080102, "InterpretationRecorder", Action.X);
  static const kInterpretationText = const BasicProfile(0x4008010B, "InterpretationText", Action.X);
  static const kInterpretationTranscriber = const BasicProfile(0x4008010A, "InterpretationTranscriber", Action.X);
  static const kIrradiationEventUID = const BasicProfile(0x00083010, "IrradiationEventUID", Action.U);
  static const kIssuerofAdmissionID = const BasicProfile(0x00380011, "IssuerofAdmissionID", Action.X);
  static const kIssuerofPatientID = const BasicProfile(0x00100021, "IssuerofPatientID", Action.X);
  static const kIssuerofServiceEpisodeID = const BasicProfile(0x00380061, "IssuerofServiceEpisodeID", Action.X);
  static const kLargePaletteColorLookupTableUID = const BasicProfile(0x00281214, "LargePaletteColorLookupTableUID", Action.U);
  static const kLastMenstrualDate = const BasicProfile(0x001021D0, "LastMenstrualDate", Action.X);
  static const kMAC = const BasicProfile(0x04000404, "MAC", Action.X);
  static const kMediaStorageSOPInstanceUID = const BasicProfile(0x00020003, "MediaStorageSOPInstanceUID", Action.U);
  static const kMedicalAlerts = const BasicProfile(0x00102000, "MedicalAlerts", Action.X);
  static const kMedicalRecordLocator = const BasicProfile(0x00101090, "MedicalRecordLocator", Action.X);
  static const kMilitaryRank = const BasicProfile(0x00101080, "MilitaryRank", Action.X);
  static const kModifiedAttributesSequence = const BasicProfile(0x04000550, "ModifiedAttributesSequence", Action.X);
  static const kModifiedImageDescription = const BasicProfile(0x00203406, "ModifiedImageDescription", Action.X);
  static const kModifyingDeviceID = const BasicProfile(0x00203401, "ModifyingDeviceID", Action.X);
  static const kModifyingDeviceManufacturer = const BasicProfile(0x00203404, "ModifyingDeviceManufacturer", Action.X);
  static const kNameofPhysician0xsReadingStudy = const BasicProfile(0x00081060, "NameofPhysician0xsReadingStudy", Action.X);
  static const kNamesofIntendedRecipientofResults = const BasicProfile(0x00401010, "NamesofIntendedRecipientofResults", Action.X);
  static const kOccupation = const BasicProfile(0x00102180, "Occupation", Action.X);
  static const kOperatorsIdentificationSequence = const BasicProfile(0x00081072, "OperatorsIdentificationSequence", Action.XD);
  static const kOperatorsName = const BasicProfile(0x00081070, "OperatorsName", Action.XZD);
  static const kOriginalAttributesSequence = const BasicProfile(0x04000561, "OriginalAttributesSequence", Action.X);
  static const kOrderCallbackPhoneNumber = const BasicProfile(0x00402010, "OrderCallbackPhoneNumber", Action.X);
  static const kOrderEnteredBy = const BasicProfile(0x00402008, "OrderEnteredBy", Action.X);
  static const kOrderEntererLocation = const BasicProfile(0x00402009, "OrderEntererLocation", Action.X);
  static const kOtherPatientIDs = const BasicProfile(0x00101000, "OtherPatientIDs", Action.X);
  static const kOtherPatientIDsSequence = const BasicProfile(0x00101002, "OtherPatientIDsSequence", Action.X);
  static const kOtherPatientNames = const BasicProfile(0x00101001, "OtherPatientNames", Action.X);
  static const kOverlayDate = const BasicProfile(0x00080024, "OverlayDate", Action.X);
  static const kOverlayTime = const BasicProfile(0x00080034, "OverlayTime", Action.X);
  static const kPaletteColorLookupTableUID = const BasicProfile(0x00281199, "PaletteColorLookupTableUID", Action.U);
  static const kParticipantSequence = const BasicProfile(0x0040A07A, "ParticipantSequence", Action.X);
  static const kPatientAddress = const BasicProfile(0x00101040, "PatientAddress", Action.X);
  static const kPatientComments = const BasicProfile(0x00104000, "PatientComments", Action.X);
  static const kPatientID = const BasicProfile(0x00100020, "PatientID", Action.Z);
  static const kPatientSexNeutered = const BasicProfile(0x00102203, "PatientSexNeutered", Action.XZ);
  static const kPatientState = const BasicProfile(0x00380500, "PatientState", Action.X);
  static const kPatientTransportArrangements = const BasicProfile(0x00401004, "PatientTransportArrangements", Action.X);
  static const kPatientsAge = const BasicProfile(0x00101010, "PatientsAge", Action.X);
  static const kPatientsBirthDate = const BasicProfile(0x00100030, "PatientsBirthDate", Action.Z);
  static const kPatientsBirthName = const BasicProfile(0x00101005, "PatientsBirthName", Action.X);
  static const kPatientsBirthTime = const BasicProfile(0x00100032, "PatientsBirthTime", Action.X);
  static const kPatientsInstitutionResidence = const BasicProfile(0x00380400, "PatientsInstitutionResidence", Action.X);
  static const kPatientsInsurancePlanCodeSequence = const BasicProfile(0x00100050, "PatientsInsurancePlanCodeSequence", Action.X);
  static const kPatientsMothersBirthName = const BasicProfile(0x00101060, "PatientsMothersBirthName", Action.X);
  static const kPatientsName = const BasicProfile(0x00100010, "PatientsName", Action.Z);
  static const kPatientsPrimaryLanguageCodeSequence = const BasicProfile(0x00100101, "PatientsPrimaryLanguageCodeSequence", Action.X);
  static const kPatientsPrimaryLanguageModifierCodeSequence = const BasicProfile(0x00100102, "PatientsPrimaryLanguageModifierCodeSequence", Action.X);
  static const kPatientsReligiousPreference = const BasicProfile(0x001021F0, "PatientsReligiousPreference", Action.X);
  static const kPatientsSex = const BasicProfile(0x00100040, "PatientsSex", Action.Z);
  static const kPatientsSize = const BasicProfile(0x00101020, "PatientsSize", Action.X);
  static const kPatientsTelephoneNumbers = const BasicProfile(0x00102154, "PatientsTelephoneNumbers", Action.X);
  static const kPatientsWeight = const BasicProfile(0x00101030, "PatientsWeight", Action.X);
  static const kPerformedLocation = const BasicProfile(0x00400243, "PerformedLocation", Action.X);
  static const kPerformedProcedureStepDescription = const BasicProfile(0x00400254, "PerformedProcedureStepDescription", Action.X);
  static const kPerformedProcedureStepEndDate = const BasicProfile(0x00400250, "PerformedProcedureStepEndDate", Action.X);
  static const kPerformedProcedureStepEndTime = const BasicProfile(0x00400251, "PerformedProcedureStepEndTime", Action.X);
  static const kPerformedProcedureStepID = const BasicProfile(0x00400253, "PerformedProcedureStepID", Action.X);
  static const kPerformedProcedureStepStartDate = const BasicProfile(0x00400244, "PerformedProcedureStepStartDate", Action.X);
  static const kPerformedProcedureStepStartTime = const BasicProfile(0x00400245, "PerformedProcedureStepStartTime", Action.X);
  static const kPerformedStationAETitle = const BasicProfile(0x00400241, "PerformedStationAETitle", Action.X);
  static const kPerformedStationGeographicLocationCodeSequence = const BasicProfile(0x00404030, "PerformedStationGeographicLocationCodeSequence", Action.X);
  static const kPerformedStationName = const BasicProfile(0x00400242, "PerformedStationName", Action.X);
  static const kPerformedStationNameCodeSequence = const BasicProfile(0x00404028, "PerformedStationNameCodeSequence", Action.X);
  static const kPerformingPhysicianIdentificationSequence = const BasicProfile(0x00081052, "PerformingPhysicianIdentificationSequence", Action.X);
  static const kPerformingPhysiciansName = const BasicProfile(0x00081050, "PerformingPhysiciansName", Action.X);
  static const kPersonAddress = const BasicProfile(0x00401102, "PersonAddress", Action.X);
  static const kPersonIdentificationCodeSequence = const BasicProfile(0x00401101, "PersonIdentificationCodeSequence", Action.D);
  static const kPersonName = const BasicProfile(0x0040A123, "PersonName", Action.D);
  static const kPersonTelephoneNumbers = const BasicProfile(0x00401103, "PersonTelephoneNumbers", Action.X);
  static const kPhysicianApprovingInterpretation = const BasicProfile(0x40080114, "PhysicianApprovingInterpretation", Action.X);
  static const kPhysician0xsReadingStudyIdentificationSequence = const BasicProfile(0x00081062, "Physician0xsReadingStudyIdentificationSequence", Action.X);
  static const kPhysician0xsofRecord = const BasicProfile(0x00081048, "Physician0xsofRecord", Action.X);
  static const kPhysician0xsofRecordIdentificationSequence = const BasicProfile(0x00081049, "Physician0xsofRecordIdentificationSequence", Action.X);
  static const kPlacerOrderNumber_ImagingServiceRequest = const BasicProfile(0x00402016, "PlacerOrderNumber_ImagingServiceRequest", Action.Z);
  static const kPlateID = const BasicProfile(0x00181004, "PlateID", Action.X);
  static const kPre_Medication = const BasicProfile(0x00400012, "Pre_Medication", Action.X);
  static const kPregnancyStatus = const BasicProfile(0x001021C0, "PregnancyStatus", Action.X);
  static const kProtocolName = const BasicProfile(0x00181030, "ProtocolName", Action.XD);
  static const kReasonfortheImagingServiceRequest = const BasicProfile(0x00402001, "ReasonfortheImagingServiceRequest", Action.X);
  static const kReasonforStudy = const BasicProfile(0x00321030, "ReasonforStudy", Action.X);
  static const kReferencedDigitalSignatureSequence = const BasicProfile(0x04000402, "ReferencedDigitalSignatureSequence", Action.X);
  static const kReferencedFrameofReferenceUID = const BasicProfile(0x30060024, "ReferencedFrameofReferenceUID", Action.U);
  static const kReferencedGeneralPurposeScheduledProcedureStepTransactionUID = const BasicProfile(0x00404023, "ReferencedGeneralPurposeScheduledProcedureStepTransactionUID", Action.U);
  static const kReferencedImageSequence = const BasicProfile(0x00081140, "ReferencedImageSequence", Action.XZU);
  static const kReferencedPatientAliasSequence = const BasicProfile(0x00380004, "ReferencedPatientAliasSequence", Action.X);
  static const kReferencedPatientSequence = const BasicProfile(0x00081120, "ReferencedPatientSequence", Action.X);
  static const kReferencedPerformedProcedureStepSequence = const BasicProfile(0x00081111, "ReferencedPerformedProcedureStepSequence", Action.XZD);
  static const kReferencedSOPInstanceMACSequence = const BasicProfile(0x04000403, "ReferencedSOPInstanceMACSequence", Action.X);
  static const kReferencedSOPInstanceUID = const BasicProfile(0x00081155, "ReferencedSOPInstanceUID", Action.U);
  static const kReferencedSOPInstanceUIDinFile = const BasicProfile(0x00041511, "ReferencedSOPInstanceUIDinFile", Action.U);
  static const kReferencedStudySequence = const BasicProfile(0x00081110, "ReferencedStudySequence", Action.XZ);
  static const kReferringPhysiciansAddress = const BasicProfile(0x00080092, "ReferringPhysiciansAddress", Action.X);
  static const kReferringPhysiciansIdentificationSequence = const BasicProfile(0x00080096, "ReferringPhysiciansIdentificationSequence", Action.X);
  static const kReferringPhysiciansName = const BasicProfile(0x00080090, "ReferringPhysiciansName", Action.Z);
  static const kReferringPhysiciansTelephoneNumbers = const BasicProfile(0x00080094, "ReferringPhysiciansTelephoneNumbers", Action.X);
  static const kRegionofResidence = const BasicProfile(0x00102152, "RegionofResidence", Action.X);
  static const kRelatedFrameofReferenceUID = const BasicProfile(0x300600C2, "RelatedFrameofReferenceUID", Action.U);
  static const kRequestAttributesSequence = const BasicProfile(0x00400275, "RequestAttributesSequence", Action.X);
  static const kRequestedContrastAgent = const BasicProfile(0x00321070, "RequestedContrastAgent", Action.X);
  static const kRequestedProcedureComments = const BasicProfile(0x00401400, "RequestedProcedureComments", Action.X);
  static const kRequestedProcedureDescription = const BasicProfile(0x00321060, "RequestedProcedureDescription", Action.XZ);
  static const kRequestedProcedureID = const BasicProfile(0x00401001, "RequestedProcedureID", Action.X);
  static const kRequestedProcedureLocation = const BasicProfile(0x00401005, "RequestedProcedureLocation", Action.X);
  static const kRequestedSOPInstanceUID = const BasicProfile(0x00001001, "RequestedSOPInstanceUID", Action.U);
  static const kRequestingPhysician = const BasicProfile(0x00321032, "RequestingPhysician", Action.X);
  static const kRequestingService = const BasicProfile(0x00321033, "RequestingService", Action.X);
  static const kResponsibleOrganization = const BasicProfile(0x00102299, "ResponsibleOrganization", Action.X);
  static const kResponsiblePerson = const BasicProfile(0x00102297, "ResponsiblePerson", Action.X);
  static const kResultsComments = const BasicProfile(0x40084000, "ResultsComments", Action.X);
  static const kResultsDistributionListSequence = const BasicProfile(0x40080118, "ResultsDistributionListSequence", Action.X);
  static const kResultsIDIssuer = const BasicProfile(0x40080042, "ResultsIDIssuer", Action.X);
  static const kReviewerName = const BasicProfile(0x300E0008, "ReviewerName", Action.XZ);
  static const kScheduledHumanPerformersSequence = const BasicProfile(0x00404034, "ScheduledHumanPerformersSequence", Action.X);
  static const kScheduledPatientInstitutionResidence = const BasicProfile(0x0038001E, "ScheduledPatientInstitutionResidence", Action.X);
  static const kScheduledPerformingPhysicianIdentificationSequence = const BasicProfile(0x0040000B, "ScheduledPerformingPhysicianIdentificationSequence", Action.X);
  static const kScheduledPerformingPhysicianName = const BasicProfile(0x00400006, "ScheduledPerformingPhysicianName", Action.X);
  static const kScheduledProcedureStepEndDate = const BasicProfile(0x00400004, "ScheduledProcedureStepEndDate", Action.X);
  static const kScheduledProcedureStepEndTime = const BasicProfile(0x00400005, "ScheduledProcedureStepEndTime", Action.X);
  static const kScheduledProcedureStepDescription = const BasicProfile(0x00400007, "ScheduledProcedureStepDescription", Action.X);
  static const kScheduledProcedureStepLocation = const BasicProfile(0x00400011, "ScheduledProcedureStepLocation", Action.X);
  static const kScheduledProcedureStepStartDate = const BasicProfile(0x00400002, "ScheduledProcedureStepStartDate", Action.X);
  static const kScheduledProcedureStepStartTime = const BasicProfile(0x00400003, "ScheduledProcedureStepStartTime", Action.X);
  static const kScheduledStationAETitle = const BasicProfile(0x00400001, "ScheduledStationAETitle", Action.X);
  static const kScheduledStationGeographicLocationCodeSequence = const BasicProfile(0x00404027, "ScheduledStationGeographicLocationCodeSequence", Action.X);
  static const kScheduledStationName = const BasicProfile(0x00400010, "ScheduledStationName", Action.X);
  static const kScheduledStationNameCodeSequence = const BasicProfile(0x00404025, "ScheduledStationNameCodeSequence", Action.X);
  static const kScheduledStudyLocation = const BasicProfile(0x00321020, "ScheduledStudyLocation", Action.X);
  static const kScheduledStudyLocationAETitle = const BasicProfile(0x00321021, "ScheduledStudyLocationAETitle", Action.X);
  static const kSeriesDate = const BasicProfile(0x00080021, "SeriesDate", Action.XD);
  static const kSeriesDescription = const BasicProfile(0x0008103E, "SeriesDescription", Action.X);
  static const kSeriesInstanceUID = const BasicProfile(0x0020000E, "SeriesInstanceUID", Action.U);
  static const kSeriesTime = const BasicProfile(0x00080031, "SeriesTime", Action.XD);
  static const kServiceEpisodeDescription = const BasicProfile(0x00380062, "ServiceEpisodeDescription", Action.X);
  static const kServiceEpisodeID = const BasicProfile(0x00380060, "ServiceEpisodeID", Action.X);
  static const kSmokingStatus = const BasicProfile(0x001021A0, "SmokingStatus", Action.X);
  static const kSOPInstanceUID = const BasicProfile(0x00080018, "SOPInstanceUID", Action.U);
  static const kSourceImageSequence = const BasicProfile(0x00082112, "SourceImageSequence", Action.XZU);
  static const kSpecialNeeds = const BasicProfile(0x00380050, "SpecialNeeds", Action.X);
  static const kStationName = const BasicProfile(0x00081010, "StationName", Action.XZD);
  static const kStorageMediaFile_setUID = const BasicProfile(0x00880140, "StorageMediaFile_setUID", Action.U);
  static const kStudyComments = const BasicProfile(0x00324000, "StudyComments", Action.X);
  static const kStudyDate = const BasicProfile(0x00080020, "StudyDate", Action.Z);
  static const kStudyDescription = const BasicProfile(0x00081030, "StudyDescription", Action.X);
  static const kStudyID = const BasicProfile(0x00200010, "StudyID", Action.Z);
  static const kStudyIDIssuer = const BasicProfile(0x00320012, "StudyIDIssuer", Action.X);
  static const kStudyInstanceUID = const BasicProfile(0x0020000D, "StudyInstanceUID", Action.U);
  static const kStudyTime = const BasicProfile(0x00080030, "StudyTime", Action.Z);
  static const kSynchronizationFrameofReferenceUID = const BasicProfile(0x00200200, "SynchronizationFrameofReferenceUID", Action.U);
  static const kTemplateExtensionCreatorUID = const BasicProfile(0x0040DB0D, "TemplateExtensionCreatorUID", Action.U);
  static const kTemplateExtensionOrganizationUID = const BasicProfile(0x0040DB0C, "TemplateExtensionOrganizationUID", Action.U);
  static const kTextComments = const BasicProfile(0x40004000, "TextComments", Action.X);
  static const kTextString = const BasicProfile(0x20300020, "TextString", Action.X);
  static const kTimezoneOffsetFromUTC = const BasicProfile(0x00080201, "TimezoneOffsetFromUTC", Action.X);
  static const kTopicAuthor = const BasicProfile(0x00880910, "TopicAuthor", Action.X);
  static const kTopicKeywords = const BasicProfile(0x00880912, "TopicKeywords", Action.X);
  static const kTopicSubject = const BasicProfile(0x00880906, "TopicSubject", Action.X);
  static const kTopicTitle = const BasicProfile(0x00880904, "TopicTitle", Action.X);
  static const kTransactionUID = const BasicProfile(0x00081195, "TransactionUID", Action.U);
  static const kUID = const BasicProfile(0x0040A124, "UID", Action.U);
  static const kVerifyingObserverIdentificationCodeSequence = const BasicProfile(0x0040A088, "VerifyingObserverIdentificationCodeSequence", Action.Z);
  static const kVerifyingObserverName = const BasicProfile(0x0040A075, "VerifyingObserverName", Action.D);
  static const kVerifyingObserverSequence = const BasicProfile(0x0040A073, "VerifyingObserverSequence", Action.D);
  static const kVerifyingOrganization = const BasicProfile(0x0040A027, "VerifyingOrganization", Action.X);
  static const kVisitComments = const BasicProfile(0x00384000, "VisitComments", Action.X);


  static const Map<int, String> map = const {
    0x00080050: Action.Z,
    0x00184000: Action.X,
    0x00400555: Action.X,
    0x00080022: Action.XZ,
    0x0008002A: Action.XD,
    0x00181400: Action.XD,
    0x00189424: Action.X,
    0x00080032: Action.XZ,
    0x00404035: Action.X,
    0x001021B0: Action.X,
    0x00380010: Action.X,
    0x00380020: Action.X,
    0x00081084: Action.X,
    0x00081080: Action.X,
    0x00380021: Action.X,
    0x00001000: Action.X,
    0x00102110: Action.X,
    0x40000010: Action.X,
    0x0040A078: Action.X,
    0x00101081: Action.X,
    0x00181007: Action.X,
    0x00400280: Action.X,
    0x00209161: Action.U,
    0x00403001: Action.X,
    0x00700084: Action.Z,
    0x00700086: Action.X,
    0x00080023: Action.ZD,
    0x0040A730: Action.X,
    0x00080033: Action.ZD,
    0x0008010D: Action.U,
    0x00180010: Action.ZD,
    0x0018A003: Action.X,
    0x00102150: Action.X,
    0x00089123: Action.U,
    0x00380300: Action.X,
    0x00080025: Action.X,
    0x00080035: Action.X,
    0x0040A07C: Action.X,
    0xFFFCFFFC: Action.X,
    0x00082111: Action.X,
    0x0018700A: Action.XD,
    0x00181000: Action.XZD,
    0x00181002: Action.U,
    0x04000100: Action.X,
    0xFFFAFFFA: Action.X,
    0x00209164: Action.U,
    0x00380040: Action.X,
    0x4008011A: Action.X,
    0x40080119: Action.X,
    0x300A0013: Action.U,
    0x00102160: Action.X,
    0x00080058: Action.U,
    0x0070031A: Action.U,
    0x00402017: Action.Z,
    0x00209158: Action.X,
    0x00200052: Action.U,
    0x00181008: Action.X,
    0x00181005: Action.X,
    0x00700001: Action.D,
    0x00404037: Action.X,
    0x00404036: Action.X,
    0x00880200: Action.X,
    0x00084000: Action.X,
    0x00204000: Action.X,
    0x00284000: Action.X,
    0x00402400: Action.X,
    0x40080300: Action.X,
    0x00080014: Action.U,
    0x00080081: Action.X,
    0x00080082: Action.XZD,
    0x00080080: Action.XZD,
    0x00081040: Action.X,
    0x00101050: Action.X,
    0x00401011: Action.X,
    0x40080111: Action.X,
    0x4008010C: Action.X,
    0x40080115: Action.X,
    0x40080202: Action.X,
    0x40080102: Action.X,
    0x4008010B: Action.X,
    0x4008010A: Action.X,
    0x00083010: Action.U,
    0x00380011: Action.X,
    0x00100021: Action.X,
    0x00380061: Action.X,
    0x00281214: Action.U,
    0x001021D0: Action.X,
    0x04000404: Action.X,
    0x00020003: Action.U,
    0x00102000: Action.X,
    0x00101090: Action.X,
    0x00101080: Action.X,
    0x04000550: Action.X,
    0x00203406: Action.X,
    0x00203401: Action.X,
    0x00203404: Action.X,
    0x00081060: Action.X,
    0x00401010: Action.X,
    0x00102180: Action.X,
    0x00081072: Action.XD,
    0x00081070: Action.XZD,
    0x04000561: Action.X,
    0x00402010: Action.X,
    0x00402008: Action.X,
    0x00402009: Action.X,
    0x00101000: Action.X,
    0x00101002: Action.X,
    0x00101001: Action.X,
    0x00080024: Action.X,
    0x00080034: Action.X,
    0x00281199: Action.U,
    0x0040A07A: Action.X,
    0x00101040: Action.X,
    0x00104000: Action.X,
    0x00100020: Action.Z,
    0x00102203: Action.XZ,
    0x00380500: Action.X,
    0x00401004: Action.X,
    0x00101010: Action.X,
    0x00100030: Action.Z,
    0x00101005: Action.X,
    0x00100032: Action.X,
    0x00380400: Action.X,
    0x00100050: Action.X,
    0x00101060: Action.X,
    0x00100010: Action.Z,
    0x00100101: Action.X,
    0x00100102: Action.X,
    0x001021F0: Action.X,
    0x00100040: Action.Z,
    0x00101020: Action.X,
    0x00102154: Action.X,
    0x00101030: Action.X,
    0x00400243: Action.X,
    0x00400254: Action.X,
    0x00400250: Action.X,
    0x00400251: Action.X,
    0x00400253: Action.X,
    0x00400244: Action.X,
    0x00400245: Action.X,
    0x00400241: Action.X,
    0x00404030: Action.X,
    0x00400242: Action.X,
    0x00404028: Action.X,
    0x00081052: Action.X,
    0x00081050: Action.X,
    0x00401102: Action.X,
    0x00401101: Action.D,
    0x0040A123: Action.D,
    0x00401103: Action.X,
    0x40080114: Action.X,
    0x00081062: Action.X,
    0x00081048: Action.X,
    0x00081049: Action.X,
    0x00402016: Action.Z,
    0x00181004: Action.X,
    0x00400012: Action.X,
    0x001021C0: Action.X,
    0x00181030: Action.XD,
    0x00402001: Action.X,
    0x00321030: Action.X,
    0x04000402: Action.X,
    0x30060024: Action.U,
    0x00404023: Action.U,
    0x00081140: Action.XZU,
    0x00380004: Action.X,
    0x00081120: Action.X,
    0x00081111: Action.XZD,
    0x04000403: Action.X,
    0x00081155: Action.U,
    0x00041511: Action.U,
    0x00081110: Action.XZ,
    0x00080092: Action.X,
    0x00080096: Action.X,
    0x00080090: Action.Z,
    0x00080094: Action.X,
    0x00102152: Action.X,
    0x300600C2: Action.U,
    0x00400275: Action.X,
    0x00321070: Action.X,
    0x00401400: Action.X,
    0x00321060: Action.XZ,
    0x00401001: Action.X,
    0x00401005: Action.X,
    0x00001001: Action.U,
    0x00321032: Action.X,
    0x00321033: Action.X,
    0x00102299: Action.X,
    0x00102297: Action.X,
    0x40084000: Action.X,
    0x40080118: Action.X,
    0x40080042: Action.X,
    0x300E0008: Action.XZ,
    0x00404034: Action.X,
    0x0038001E: Action.X,
    0x0040000B: Action.X,
    0x00400006: Action.X,
    0x00400004: Action.X,
    0x00400005: Action.X,
    0x00400007: Action.X,
    0x00400011: Action.X,
    0x00400002: Action.X,
    0x00400003: Action.X,
    0x00400001: Action.X,
    0x00404027: Action.X,
    0x00400010: Action.X,
    0x00404025: Action.X,
    0x00321020: Action.X,
    0x00321021: Action.X,
    0x00080021: Action.XD,
    0x0008103E: Action.X,
    0x0020000E: Action.U,
    0x00080031: Action.XD,
    0x00380062: Action.X,
    0x00380060: Action.X,
    0x001021A0: Action.X,
    0x00080018: Action.U,
    0x00082112: Action.XZU,
    0x00380050: Action.X,
    0x00081010: Action.XZD,
    0x00880140: Action.U,
    0x00324000: Action.X,
    0x00080020: Action.Z,
    0x00081030: Action.X,
    0x00200010: Action.Z,
    0x00320012: Action.X,
    0x0020000D: Action.U,
    0x00080030: Action.Z,
    0x00200200: Action.U,
    0x0040DB0D: Action.U,
    0x0040DB0C: Action.U,
    0x40004000: Action.X,
    0x20300020: Action.X,
    0x00080201: Action.X,
    0x00880910: Action.X,
    0x00880912: Action.X,
    0x00880906: Action.X,
    0x00880904: Action.X,
    0x00081195: Action.U,
    0x0040A124: Action.U,
    0x0040A088: Action.Z,
    0x0040A075: Action.D,
    0x0040A073: Action.D,
    0x0040A027: Action.X,
    0x00384000: Action.X};

  static const List<int> tags = const [
    0x00080050,
    0x00184000,
    0x00400555,
    0x00080022,
    0x0008002A,
    0x00181400,
    0x00189424,
    0x00080032,
    0x00404035,
    0x001021B0,
    0x00380010,
    0x00380020,
    0x00081084,
    0x00081080,
    0x00380021,
    0x00001000,
    0x00102110,
    0x40000010,
    0x0040A078,
    0x00101081,
    0x00181007,
    0x00400280,
    0x00209161,
    0x00403001,
    0x00700084,
    0x00700086,
    0x00080023,
    0x0040A730,
    0x00080033,
    0x0008010D,
    0x00180010,
    0x0018A003,
    0x00102150,
    0x00089123,
    0x00380300,
    0x00080025,
    0x00080035,
    0x0040A07C,
    0xFFFCFFFC,
    0x00082111,
    0x0018700A,
    0x00181000,
    0x00181002,
    0x04000100,
    0xFFFAFFFA,
    0x00209164,
    0x00380040,
    0x4008011A,
    0x40080119,
    0x300A0013,
    0x00102160,
    0x00080058,
    0x0070031A,
    0x00402017,
    0x00209158,
    0x00200052,
    0x00181008,
    0x00181005,
    0x00700001,
    0x00404037,
    0x00404036,
    0x00880200,
    0x00084000,
    0x00204000,
    0x00284000,
    0x00402400,
    0x40080300,
    0x00080014,
    0x00080081,
    0x00080082,
    0x00080080,
    0x00081040,
    0x00101050,
    0x00401011,
    0x40080111,
    0x4008010C,
    0x40080115,
    0x40080202,
    0x40080102,
    0x4008010B,
    0x4008010A,
    0x00083010,
    0x00380011,
    0x00100021,
    0x00380061,
    0x00281214,
    0x001021D0,
    0x04000404,
    0x00020003,
    0x00102000,
    0x00101090,
    0x00101080,
    0x04000550,
    0x00203406,
    0x00203401,
    0x00203404,
    0x00081060,
    0x00401010,
    0x00102180,
    0x00081072,
    0x00081070,
    0x04000561,
    0x00402010,
    0x00402008,
    0x00402009,
    0x00101000,
    0x00101002,
    0x00101001,
    0x00080024,
    0x00080034,
    0x00281199,
    0x0040A07A,
    0x00101040,
    0x00104000,
    0x00100020,
    0x00102203,
    0x00380500,
    0x00401004,
    0x00101010,
    0x00100030,
    0x00101005,
    0x00100032,
    0x00380400,
    0x00100050,
    0x00101060,
    0x00100010,
    0x00100101,
    0x00100102,
    0x001021F0,
    0x00100040,
    0x00101020,
    0x00102154,
    0x00101030,
    0x00400243,
    0x00400254,
    0x00400250,
    0x00400251,
    0x00400253,
    0x00400244,
    0x00400245,
    0x00400241,
    0x00404030,
    0x00400242,
    0x00404028,
    0x00081052,
    0x00081050,
    0x00401102,
    0x00401101,
    0x0040A123,
    0x00401103,
    0x40080114,
    0x00081062,
    0x00081048,
    0x00081049,
    0x00402016,
    0x00181004,
    0x00400012,
    0x001021C0,
    0x00181030,
    0x00402001,
    0x00321030,
    0x04000402,
    0x30060024,
    0x00404023,
    0x00081140,
    0x00380004,
    0x00081120,
    0x00081111,
    0x04000403,
    0x00081155,
    0x00041511,
    0x00081110,
    0x00080092,
    0x00080096,
    0x00080090,
    0x00080094,
    0x00102152,
    0x300600C2,
    0x00400275,
    0x00321070,
    0x00401400,
    0x00321060,
    0x00401001,
    0x00401005,
    0x00001001,
    0x00321032,
    0x00321033,
    0x00102299,
    0x00102297,
    0x40084000,
    0x40080118,
    0x40080042,
    0x300E0008,
    0x00404034,
    0x0038001E,
    0x0040000B,
    0x00400006,
    0x00400004,
    0x00400005,
    0x00400007,
    0x00400011,
    0x00400002,
    0x00400003,
    0x00400001,
    0x00404027,
    0x00400010,
    0x00404025,
    0x00321020,
    0x00321021,
    0x00080021,
    0x0008103E,
    0x0020000E,
    0x00080031,
    0x00380062,
    0x00380060,
    0x001021A0,
    0x00080018,
    0x00082112,
    0x00380050,
    0x00081010,
    0x00880140,
    0x00324000,
    0x00080020,
    0x00081030,
    0x00200010,
    0x00320012,
    0x0020000D,
    0x00080030,
    0x00200200,
    0x0040DB0D,
    0x0040DB0C,
    0x40004000,
    0x20300020,
    0x00080201,
    0x00880910,
    0x00880912,
    0x00880906,
    0x00880904,
    0x00081195,
    0x0040A124,
    0x0040A088,
    0x0040A075,
    0x0040A073,
    0x0040A027,
    0x00384000];

  static const List<Action> actions = const [
    Action.Z,
    Action.X,
    Action.X,
    Action.XZ,
    Action.XD,
    Action.XD,
    Action.X,
    Action.XZ,
    Action.X,
    Action.X,
    Action.X,
    Action.X,
    Action.X,
    Action.X,
    Action.X,
    Action.X,
    Action.X,
    Action.X,
    Action.X,
    Action.X,
    Action.X,
    Action.X,
    Action.U,
    Action.X,
    Action.Z,
    Action.X,
    Action.ZD,
    Action.X,
    Action.ZD,
    Action.U,
    Action.ZD,
    Action.X,
    Action.X,
    Action.U,
    Action.X,
    Action.X,
    Action.X,
    Action.X,
    Action.X,
    Action.X,
    Action.XD,
    Action.XZD,
    Action.U,
    Action.X,
    Action.X,
    Action.U,
    Action.X,
    Action.X,
    Action.X,
    Action.U,
    Action.X,
    Action.U,
    Action.U,
    Action.Z,
    Action.X,
    Action.U,
    Action.X,
    Action.X,
    Action.D,
    Action.X,
    Action.X,
    Action.X,
    Action.X,
    Action.X,
    Action.X,
    Action.X,
    Action.X,
    Action.U,
    Action.X,
    Action.XZD,
    Action.XZD,
    Action.X,
    Action.X,
    Action.X,
    Action.X,
    Action.X,
    Action.X,
    Action.X,
    Action.X,
    Action.X,
    Action.X,
    Action.U,
    Action.X,
    Action.X,
    Action.X,
    Action.U,
    Action.X,
    Action.X,
    Action.U,
    Action.X,
    Action.X,
    Action.X,
    Action.X,
    Action.X,
    Action.X,
    Action.X,
    Action.X,
    Action.X,
    Action.X,
    Action.XD,
    Action.XZD,
    Action.X,
    Action.X,
    Action.X,
    Action.X,
    Action.X,
    Action.X,
    Action.X,
    Action.X,
    Action.X,
    Action.U,
    Action.X,
    Action.X,
    Action.X,
    Action.Z,
    Action.XZ,
    Action.X,
    Action.X,
    Action.X,
    Action.Z,
    Action.X,
    Action.X,
    Action.X,
    Action.X,
    Action.X,
    Action.Z,
    Action.X,
    Action.X,
    Action.X,
    Action.Z,
    Action.X,
    Action.X,
    Action.X,
    Action.X,
    Action.X,
    Action.X,
    Action.X,
    Action.X,
    Action.X,
    Action.X,
    Action.X,
    Action.X,
    Action.X,
    Action.X,
    Action.X,
    Action.X,
    Action.X,
    Action.D,
    Action.D,
    Action.X,
    Action.X,
    Action.X,
    Action.X,
    Action.X,
    Action.Z,
    Action.X,
    Action.X,
    Action.X,
    Action.XD,
    Action.X,
    Action.X,
    Action.X,
    Action.U,
    Action.U,
    Action.XZU,
    Action.X,
    Action.X,
    Action.XZD,
    Action.X,
    Action.U,
    Action.U,
    Action.XZ,
    Action.X,
    Action.X,
    Action.Z,
    Action.X,
    Action.X,
    Action.U,
    Action.X,
    Action.X,
    Action.X,
    Action.XZ,
    Action.X,
    Action.X,
    Action.U,
    Action.X,
    Action.X,
    Action.X,
    Action.X,
    Action.X,
    Action.X,
    Action.X,
    Action.XZ,
    Action.X,
    Action.X,
    Action.X,
    Action.X,
    Action.X,
    Action.X,
    Action.X,
    Action.X,
    Action.X,
    Action.X,
    Action.X,
    Action.X,
    Action.X,
    Action.X,
    Action.X,
    Action.X,
    Action.XD,
    Action.X,
    Action.U,
    Action.XD,
    Action.X,
    Action.X,
    Action.X,
    Action.U,
    Action.XZU,
    Action.X,
    Action.XZD,
    Action.U,
    Action.X,
    Action.Z,
    Action.X,
    Action.Z,
    Action.X,
    Action.U,
    Action.Z,
    Action.U,
    Action.U,
    Action.U,
    Action.X,
    Action.X,
    Action.X,
    Action.X,
    Action.X,
    Action.X,
    Action.X,
    Action.U,
    Action.U,
    Action.Z,
    Action.D,
    Action.D,
    Action.X,
    Action.X];



}
  