// Copyright (c) 2016, Open DICOMweb Project. All rights reserved.
// Use of this source code is governed by the open source license
// that can be found in the LICENSE file.
// Author: Jim Philbin <jfphilbin@gmail.edu> -
// See the AUTHORS file for other contributors.

// *** This file generated by '../bin/generate/generate_basic_profile.dart' ***
// ----------------------------------------------------------

import 'package:deid/src/deid/action.dart';

class CleanStructuredContentOption {
  final int tag;
  final String keyword;
  final Action action;

  const CleanStructuredContentOption(this.tag, this.keyword, this.action);

  static lookup(int tag) => map[tag];

  static const kAcquisitionContextSequence = const CleanStructuredContentOption(0x00400555, "AcquisitionContextSequence", Action.C);
  static const kContentSequence = const CleanStructuredContentOption(0x0040A730, "ContentSequence", Action.C);


  static const Map<int, String> map = const {
    0x00400555: kAcquisitionContextSequence,
    0x0040A730: kContentSequence};

  static const List<int> keys = const [
    0x00400555,
    0x0040A730];

  static const List<String> values = const [
    kAcquisitionContextSequence,
    kContentSequence];



}
  