// Copyright (c) 2016, Open DICOMweb Project. All rights reserved.
// Use of this source code is governed by the open source license
// that can be found in the LICENSE file.
// Author: Jim Philbin <jfphilbin@gmail.edu> -
// See the AUTHORS file for other contributors.

// *** This file generated by '../bin/generate/generate_basic_profile.dart' ***
// ----------------------------------------------------------

import 'package:deid/src/deid/action.dart';

class CleanDescriptorsOption {
  final int tag;
  final String keyword;
  final Action action;

  const CleanDescriptorsOption(this.tag, this.keyword, this.action);

  static lookup(int tag) => map[tag];

  static const kAcquisitionComments = const CleanDescriptorsOption(0x00184000, "AcquisitionComments", Action.C);
  static const kAcquisitionDeviceProcessingDescription = const CleanDescriptorsOption(0x00181400, "AcquisitionDeviceProcessingDescription", Action.C);
  static const kAcquisitionProtocolDescription = const CleanDescriptorsOption(0x00189424, "AcquisitionProtocolDescription", Action.C);
  static const kAdditionalPatientsHistory = const CleanDescriptorsOption(0x001021B0, "AdditionalPatientsHistory", Action.C);
  static const kAdmittingDiagnosesCodeSequence = const CleanDescriptorsOption(0x00081084, "AdmittingDiagnosesCodeSequence", Action.C);
  static const kAdmittingDiagnosesDescription = const CleanDescriptorsOption(0x00081080, "AdmittingDiagnosesDescription", Action.C);
  static const kAllergies = const CleanDescriptorsOption(0x00102110, "Allergies", Action.C);
  static const kCommentsonthePerformedProcedureStep = const CleanDescriptorsOption(0x00400280, "CommentsonthePerformedProcedureStep", Action.C);
  static const kContrastBolusAgent = const CleanDescriptorsOption(0x00180010, "ContrastBolusAgent", Action.C);
  static const kContributionDescription = const CleanDescriptorsOption(0x0018A003, "ContributionDescription", Action.C);
  static const kDerivationDescription = const CleanDescriptorsOption(0x00082111, "DerivationDescription", Action.C);
  static const kDischargeDiagnosisDescription = const CleanDescriptorsOption(0x00380040, "DischargeDiagnosisDescription", Action.C);
  static const kFrameComments = const CleanDescriptorsOption(0x00209158, "FrameComments", Action.C);
  static const kIdentifyingComments = const CleanDescriptorsOption(0x00084000, "IdentifyingComments", Action.C);
  static const kImageComments = const CleanDescriptorsOption(0x00204000, "ImageComments", Action.C);
  static const kImagingServiceRequestComments = const CleanDescriptorsOption(0x00402400, "ImagingServiceRequestComments", Action.C);
  static const kImpressions = const CleanDescriptorsOption(0x40080300, "Impressions", Action.C);
  static const kInterpretationDiagnosisDescription = const CleanDescriptorsOption(0x40080115, "InterpretationDiagnosisDescription", Action.C);
  static const kInterpretationText = const CleanDescriptorsOption(0x4008010B, "InterpretationText", Action.C);
  static const kMedicalAlerts = const CleanDescriptorsOption(0x00102000, "MedicalAlerts", Action.C);
  static const kOccupation = const CleanDescriptorsOption(0x00102180, "Occupation", Action.C);
  static const kPatientComments = const CleanDescriptorsOption(0x00104000, "PatientComments", Action.C);
  static const kPatientState = const CleanDescriptorsOption(0x00380500, "PatientState", Action.C);
  static const kPerformedProcedureStepDescription = const CleanDescriptorsOption(0x00400254, "PerformedProcedureStepDescription", Action.C);
  static const kProtocolName = const CleanDescriptorsOption(0x00181030, "ProtocolName", Action.C);
  static const kReasonfortheImagingServiceRequest = const CleanDescriptorsOption(0x00402001, "ReasonfortheImagingServiceRequest", Action.C);
  static const kReasonforStudy = const CleanDescriptorsOption(0x00321030, "ReasonforStudy", Action.C);
  static const kRequestAttributesSequence = const CleanDescriptorsOption(0x00400275, "RequestAttributesSequence", Action.C);
  static const kRequestedContrastAgent = const CleanDescriptorsOption(0x00321070, "RequestedContrastAgent", Action.C);
  static const kRequestedProcedureComments = const CleanDescriptorsOption(0x00401400, "RequestedProcedureComments", Action.C);
  static const kRequestedProcedureDescription = const CleanDescriptorsOption(0x00321060, "RequestedProcedureDescription", Action.C);
  static const kResultsComments = const CleanDescriptorsOption(0x40084000, "ResultsComments", Action.C);
  static const kScheduledProcedureStepDescription = const CleanDescriptorsOption(0x00400007, "ScheduledProcedureStepDescription", Action.C);
  static const kSeriesDescription = const CleanDescriptorsOption(0x0008103E, "SeriesDescription", Action.C);
  static const kServiceEpisodeDescription = const CleanDescriptorsOption(0x00380062, "ServiceEpisodeDescription", Action.C);
  static const kStudyComments = const CleanDescriptorsOption(0x00324000, "StudyComments", Action.C);
  static const kStudyDescription = const CleanDescriptorsOption(0x00081030, "StudyDescription", Action.C);
  static const kVisitComments = const CleanDescriptorsOption(0x00384000, "VisitComments", Action.C);


  static const Map<int, String> map = const {
    0x00184000: kAcquisitionComments,
    0x00181400: kAcquisitionDeviceProcessingDescription,
    0x00189424: kAcquisitionProtocolDescription,
    0x001021B0: kAdditionalPatientsHistory,
    0x00081084: kAdmittingDiagnosesCodeSequence,
    0x00081080: kAdmittingDiagnosesDescription,
    0x00102110: kAllergies,
    0x00400280: kCommentsonthePerformedProcedureStep,
    0x00180010: kContrastBolusAgent,
    0x0018A003: kContributionDescription,
    0x00082111: kDerivationDescription,
    0x00380040: kDischargeDiagnosisDescription,
    0x00209158: kFrameComments,
    0x00084000: kIdentifyingComments,
    0x00204000: kImageComments,
    0x00402400: kImagingServiceRequestComments,
    0x40080300: kImpressions,
    0x40080115: kInterpretationDiagnosisDescription,
    0x4008010B: kInterpretationText,
    0x00102000: kMedicalAlerts,
    0x00102180: kOccupation,
    0x00104000: kPatientComments,
    0x00380500: kPatientState,
    0x00400254: kPerformedProcedureStepDescription,
    0x00181030: kProtocolName,
    0x00402001: kReasonfortheImagingServiceRequest,
    0x00321030: kReasonforStudy,
    0x00400275: kRequestAttributesSequence,
    0x00321070: kRequestedContrastAgent,
    0x00401400: kRequestedProcedureComments,
    0x00321060: kRequestedProcedureDescription,
    0x40084000: kResultsComments,
    0x00400007: kScheduledProcedureStepDescription,
    0x0008103E: kSeriesDescription,
    0x00380062: kServiceEpisodeDescription,
    0x00324000: kStudyComments,
    0x00081030: kStudyDescription,
    0x00384000: kVisitComments};

  static const List<int> keys = const [
    0x00184000,
    0x00181400,
    0x00189424,
    0x001021B0,
    0x00081084,
    0x00081080,
    0x00102110,
    0x00400280,
    0x00180010,
    0x0018A003,
    0x00082111,
    0x00380040,
    0x00209158,
    0x00084000,
    0x00204000,
    0x00402400,
    0x40080300,
    0x40080115,
    0x4008010B,
    0x00102000,
    0x00102180,
    0x00104000,
    0x00380500,
    0x00400254,
    0x00181030,
    0x00402001,
    0x00321030,
    0x00400275,
    0x00321070,
    0x00401400,
    0x00321060,
    0x40084000,
    0x00400007,
    0x0008103E,
    0x00380062,
    0x00324000,
    0x00081030,
    0x00384000];

  static const List<String> values = const [
    kAcquisitionComments,
    kAcquisitionDeviceProcessingDescription,
    kAcquisitionProtocolDescription,
    kAdditionalPatientsHistory,
    kAdmittingDiagnosesCodeSequence,
    kAdmittingDiagnosesDescription,
    kAllergies,
    kCommentsonthePerformedProcedureStep,
    kContrastBolusAgent,
    kContributionDescription,
    kDerivationDescription,
    kDischargeDiagnosisDescription,
    kFrameComments,
    kIdentifyingComments,
    kImageComments,
    kImagingServiceRequestComments,
    kImpressions,
    kInterpretationDiagnosisDescription,
    kInterpretationText,
    kMedicalAlerts,
    kOccupation,
    kPatientComments,
    kPatientState,
    kPerformedProcedureStepDescription,
    kProtocolName,
    kReasonfortheImagingServiceRequest,
    kReasonforStudy,
    kRequestAttributesSequence,
    kRequestedContrastAgent,
    kRequestedProcedureComments,
    kRequestedProcedureDescription,
    kResultsComments,
    kScheduledProcedureStepDescription,
    kSeriesDescription,
    kServiceEpisodeDescription,
    kStudyComments,
    kStudyDescription,
    kVisitComments];



}
  