// Copyright (c) 2016, Open DICOMweb Project. All rights reserved.
// Use of this source code is governed by the open source license
// that can be found in the LICENSE file.
// Author: Jim Philbin <jfphilbin@gmail.edu> -
// See the AUTHORS file for other contributors.

// *** This file generated by '../bin/generate/generate_basic_profile.dart' ***
// ----------------------------------------------------------

import 'package:deid/src/deid/action.dart';

class RetainDeviceIdentificationOption {
  final int tag;
  final String keyword;
  final Action action;

  const RetainDeviceIdentificationOption(this.tag, this.keyword, this.action);

  static lookup(int tag) => tagToRetainDeviceIdentification[tag];

    static const kAccessionNumber = const RetainDeviceIdentificationOption(0x00080050, "AccessionNumber", null);
  static const kAcquisitionComments = const RetainDeviceIdentificationOption(0x00184000, "AcquisitionComments", null);
  static const kAcquisitionContextSequence = const RetainDeviceIdentificationOption(0x00400555, "AcquisitionContextSequence", null);
  static const kAcquisitionDate = const RetainDeviceIdentificationOption(0x00080022, "AcquisitionDate", null);
  static const kAcquisitionDateTime = const RetainDeviceIdentificationOption(0x0008002A, "AcquisitionDateTime", null);
  static const kAcquisitionDeviceProcessingDescription = const RetainDeviceIdentificationOption(0x00181400, "AcquisitionDeviceProcessingDescription", null);
  static const kAcquisitionProtocolDescription = const RetainDeviceIdentificationOption(0x00189424, "AcquisitionProtocolDescription", null);
  static const kAcquisitionTime = const RetainDeviceIdentificationOption(0x00080032, "AcquisitionTime", null);
  static const kActualHumanPerformersSequence = const RetainDeviceIdentificationOption(0x00404035, "ActualHumanPerformersSequence", null);
  static const kAdditionalPatientsHistory = const RetainDeviceIdentificationOption(0x001021B0, "AdditionalPatientsHistory", null);
  static const kAdmissionID = const RetainDeviceIdentificationOption(0x00380010, "AdmissionID", null);
  static const kAdmittingDate = const RetainDeviceIdentificationOption(0x00380020, "AdmittingDate", null);
  static const kAdmittingDiagnosesCodeSequence = const RetainDeviceIdentificationOption(0x00081084, "AdmittingDiagnosesCodeSequence", null);
  static const kAdmittingDiagnosesDescription = const RetainDeviceIdentificationOption(0x00081080, "AdmittingDiagnosesDescription", null);
  static const kAdmittingTime = const RetainDeviceIdentificationOption(0x00380021, "AdmittingTime", null);
  static const kAffectedSOPInstanceUID = const RetainDeviceIdentificationOption(0x00001000, "AffectedSOPInstanceUID", null);
  static const kAllergies = const RetainDeviceIdentificationOption(0x00102110, "Allergies", null);
  static const kArbitrary = const RetainDeviceIdentificationOption(0x40000010, "Arbitrary", null);
  static const kAuthorObserverSequence = const RetainDeviceIdentificationOption(0x0040A078, "AuthorObserverSequence", null);
  static const kBranchofService = const RetainDeviceIdentificationOption(0x00101081, "BranchofService", null);
  static const kCassetteID = const RetainDeviceIdentificationOption(0x00181007, "CassetteID", Action.K);
  static const kCommentsonthePerformedProcedureStep = const RetainDeviceIdentificationOption(0x00400280, "CommentsonthePerformedProcedureStep", null);
  static const kConcatenationUID = const RetainDeviceIdentificationOption(0x00209161, "ConcatenationUID", null);
  static const kConfidentialityConstraintonPatientDataDescription = const RetainDeviceIdentificationOption(0x00403001, "ConfidentialityConstraintonPatientDataDescription", null);
  static const kContentCreatorsName = const RetainDeviceIdentificationOption(0x00700084, "ContentCreatorsName", null);
  static const kContentCreatorsIdentificationCodeSequence = const RetainDeviceIdentificationOption(0x00700086, "ContentCreatorsIdentificationCodeSequence", null);
  static const kContentDate = const RetainDeviceIdentificationOption(0x00080023, "ContentDate", null);
  static const kContentSequence = const RetainDeviceIdentificationOption(0x0040A730, "ContentSequence", null);
  static const kContentTime = const RetainDeviceIdentificationOption(0x00080033, "ContentTime", null);
  static const kContextGroupExtensionCreatorUID = const RetainDeviceIdentificationOption(0x0008010D, "ContextGroupExtensionCreatorUID", null);
  static const kContrastBolusAgent = const RetainDeviceIdentificationOption(0x00180010, "ContrastBolusAgent", null);
  static const kContributionDescription = const RetainDeviceIdentificationOption(0x0018A003, "ContributionDescription", null);
  static const kCountryofResidence = const RetainDeviceIdentificationOption(0x00102150, "CountryofResidence", null);
  static const kCreatorVersionUID = const RetainDeviceIdentificationOption(0x00089123, "CreatorVersionUID", null);
  static const kCurrentPatientLocation = const RetainDeviceIdentificationOption(0x00380300, "CurrentPatientLocation", null);
  static const kCurveDate = const RetainDeviceIdentificationOption(0x00080025, "CurveDate", null);
  static const kCurveTime = const RetainDeviceIdentificationOption(0x00080035, "CurveTime", null);
  static const kCustodialOrganizationSequence = const RetainDeviceIdentificationOption(0x0040A07C, "CustodialOrganizationSequence", null);
  static const kDataSetTrailingPadding = const RetainDeviceIdentificationOption(0xFFFCFFFC, "DataSetTrailingPadding", null);
  static const kDerivationDescription = const RetainDeviceIdentificationOption(0x00082111, "DerivationDescription", null);
  static const kDetectorID = const RetainDeviceIdentificationOption(0x0018700A, "DetectorID", Action.K);
  static const kDeviceSerialNumber = const RetainDeviceIdentificationOption(0x00181000, "DeviceSerialNumber", Action.K);
  static const kDeviceUID = const RetainDeviceIdentificationOption(0x00181002, "DeviceUID", Action.K);
  static const kDigitalSignatureUID = const RetainDeviceIdentificationOption(0x04000100, "DigitalSignatureUID", null);
  static const kDigitalSignaturesSequence = const RetainDeviceIdentificationOption(0xFFFAFFFA, "DigitalSignaturesSequence", null);
  static const kDimensionOrganizationUID = const RetainDeviceIdentificationOption(0x00209164, "DimensionOrganizationUID", null);
  static const kDischargeDiagnosisDescription = const RetainDeviceIdentificationOption(0x00380040, "DischargeDiagnosisDescription", null);
  static const kDistributionAddress = const RetainDeviceIdentificationOption(0x4008011A, "DistributionAddress", null);
  static const kDistributionName = const RetainDeviceIdentificationOption(0x40080119, "DistributionName", null);
  static const kDoseReferenceUID = const RetainDeviceIdentificationOption(0x300A0013, "DoseReferenceUID", null);
  static const kEthnicGroup = const RetainDeviceIdentificationOption(0x00102160, "EthnicGroup", null);
  static const kFailedSOPInstanceUIDList = const RetainDeviceIdentificationOption(0x00080058, "FailedSOPInstanceUIDList", null);
  static const kFiducialUID = const RetainDeviceIdentificationOption(0x0070031A, "FiducialUID", null);
  static const kFillerOrderNumber_ImagingServiceRequest = const RetainDeviceIdentificationOption(0x00402017, "FillerOrderNumber_ImagingServiceRequest", null);
  static const kFrameComments = const RetainDeviceIdentificationOption(0x00209158, "FrameComments", null);
  static const kFrameofReferenceUID = const RetainDeviceIdentificationOption(0x00200052, "FrameofReferenceUID", null);
  static const kGantryID = const RetainDeviceIdentificationOption(0x00181008, "GantryID", Action.K);
  static const kGeneratorID = const RetainDeviceIdentificationOption(0x00181005, "GeneratorID", Action.K);
  static const kGraphicAnnotationSequence = const RetainDeviceIdentificationOption(0x00700001, "GraphicAnnotationSequence", null);
  static const kHumanPerformersName = const RetainDeviceIdentificationOption(0x00404037, "HumanPerformersName", null);
  static const kHumanPerformersOrganization = const RetainDeviceIdentificationOption(0x00404036, "HumanPerformersOrganization", null);
  static const kIconImageSequence0xseeNote12 = const RetainDeviceIdentificationOption(0x00880200, "IconImageSequence0xseeNote12", null);
  static const kIdentifyingComments = const RetainDeviceIdentificationOption(0x00084000, "IdentifyingComments", null);
  static const kImageComments = const RetainDeviceIdentificationOption(0x00204000, "ImageComments", null);
  static const kImagePresentationComments = const RetainDeviceIdentificationOption(0x00284000, "ImagePresentationComments", null);
  static const kImagingServiceRequestComments = const RetainDeviceIdentificationOption(0x00402400, "ImagingServiceRequestComments", null);
  static const kImpressions = const RetainDeviceIdentificationOption(0x40080300, "Impressions", null);
  static const kInstanceCreatorUID = const RetainDeviceIdentificationOption(0x00080014, "InstanceCreatorUID", null);
  static const kInstitutionAddress = const RetainDeviceIdentificationOption(0x00080081, "InstitutionAddress", null);
  static const kInstitutionCodeSequence = const RetainDeviceIdentificationOption(0x00080082, "InstitutionCodeSequence", null);
  static const kInstitutionName = const RetainDeviceIdentificationOption(0x00080080, "InstitutionName", null);
  static const kInstitutionalDepartmentName = const RetainDeviceIdentificationOption(0x00081040, "InstitutionalDepartmentName", null);
  static const kInsurancePlanIdentification = const RetainDeviceIdentificationOption(0x00101050, "InsurancePlanIdentification", null);
  static const kIntendedRecipientsofResultsIdentificationSequence = const RetainDeviceIdentificationOption(0x00401011, "IntendedRecipientsofResultsIdentificationSequence", null);
  static const kInterpretationApproverSequence = const RetainDeviceIdentificationOption(0x40080111, "InterpretationApproverSequence", null);
  static const kInterpretationAuthor = const RetainDeviceIdentificationOption(0x4008010C, "InterpretationAuthor", null);
  static const kInterpretationDiagnosisDescription = const RetainDeviceIdentificationOption(0x40080115, "InterpretationDiagnosisDescription", null);
  static const kInterpretationIDIssuer = const RetainDeviceIdentificationOption(0x40080202, "InterpretationIDIssuer", null);
  static const kInterpretationRecorder = const RetainDeviceIdentificationOption(0x40080102, "InterpretationRecorder", null);
  static const kInterpretationText = const RetainDeviceIdentificationOption(0x4008010B, "InterpretationText", null);
  static const kInterpretationTranscriber = const RetainDeviceIdentificationOption(0x4008010A, "InterpretationTranscriber", null);
  static const kIrradiationEventUID = const RetainDeviceIdentificationOption(0x00083010, "IrradiationEventUID", null);
  static const kIssuerofAdmissionID = const RetainDeviceIdentificationOption(0x00380011, "IssuerofAdmissionID", null);
  static const kIssuerofPatientID = const RetainDeviceIdentificationOption(0x00100021, "IssuerofPatientID", null);
  static const kIssuerofServiceEpisodeID = const RetainDeviceIdentificationOption(0x00380061, "IssuerofServiceEpisodeID", null);
  static const kLargePaletteColorLookupTableUID = const RetainDeviceIdentificationOption(0x00281214, "LargePaletteColorLookupTableUID", null);
  static const kLastMenstrualDate = const RetainDeviceIdentificationOption(0x001021D0, "LastMenstrualDate", null);
  static const kMAC = const RetainDeviceIdentificationOption(0x04000404, "MAC", null);
  static const kMediaStorageSOPInstanceUID = const RetainDeviceIdentificationOption(0x00020003, "MediaStorageSOPInstanceUID", null);
  static const kMedicalAlerts = const RetainDeviceIdentificationOption(0x00102000, "MedicalAlerts", null);
  static const kMedicalRecordLocator = const RetainDeviceIdentificationOption(0x00101090, "MedicalRecordLocator", null);
  static const kMilitaryRank = const RetainDeviceIdentificationOption(0x00101080, "MilitaryRank", null);
  static const kModifiedAttributesSequence = const RetainDeviceIdentificationOption(0x04000550, "ModifiedAttributesSequence", null);
  static const kModifiedImageDescription = const RetainDeviceIdentificationOption(0x00203406, "ModifiedImageDescription", null);
  static const kModifyingDeviceID = const RetainDeviceIdentificationOption(0x00203401, "ModifyingDeviceID", null);
  static const kModifyingDeviceManufacturer = const RetainDeviceIdentificationOption(0x00203404, "ModifyingDeviceManufacturer", null);
  static const kNameofPhysician0xsReadingStudy = const RetainDeviceIdentificationOption(0x00081060, "NameofPhysician0xsReadingStudy", null);
  static const kNamesofIntendedRecipientofResults = const RetainDeviceIdentificationOption(0x00401010, "NamesofIntendedRecipientofResults", null);
  static const kOccupation = const RetainDeviceIdentificationOption(0x00102180, "Occupation", null);
  static const kOperatorsIdentificationSequence = const RetainDeviceIdentificationOption(0x00081072, "OperatorsIdentificationSequence", null);
  static const kOperatorsName = const RetainDeviceIdentificationOption(0x00081070, "OperatorsName", null);
  static const kOriginalAttributesSequence = const RetainDeviceIdentificationOption(0x04000561, "OriginalAttributesSequence", null);
  static const kOrderCallbackPhoneNumber = const RetainDeviceIdentificationOption(0x00402010, "OrderCallbackPhoneNumber", null);
  static const kOrderEnteredBy = const RetainDeviceIdentificationOption(0x00402008, "OrderEnteredBy", null);
  static const kOrderEntererLocation = const RetainDeviceIdentificationOption(0x00402009, "OrderEntererLocation", null);
  static const kOtherPatientIDs = const RetainDeviceIdentificationOption(0x00101000, "OtherPatientIDs", null);
  static const kOtherPatientIDsSequence = const RetainDeviceIdentificationOption(0x00101002, "OtherPatientIDsSequence", null);
  static const kOtherPatientNames = const RetainDeviceIdentificationOption(0x00101001, "OtherPatientNames", null);
  static const kOverlayDate = const RetainDeviceIdentificationOption(0x00080024, "OverlayDate", null);
  static const kOverlayTime = const RetainDeviceIdentificationOption(0x00080034, "OverlayTime", null);
  static const kPaletteColorLookupTableUID = const RetainDeviceIdentificationOption(0x00281199, "PaletteColorLookupTableUID", null);
  static const kParticipantSequence = const RetainDeviceIdentificationOption(0x0040A07A, "ParticipantSequence", null);
  static const kPatientAddress = const RetainDeviceIdentificationOption(0x00101040, "PatientAddress", null);
  static const kPatientComments = const RetainDeviceIdentificationOption(0x00104000, "PatientComments", null);
  static const kPatientID = const RetainDeviceIdentificationOption(0x00100020, "PatientID", null);
  static const kPatientSexNeutered = const RetainDeviceIdentificationOption(0x00102203, "PatientSexNeutered", null);
  static const kPatientState = const RetainDeviceIdentificationOption(0x00380500, "PatientState", null);
  static const kPatientTransportArrangements = const RetainDeviceIdentificationOption(0x00401004, "PatientTransportArrangements", null);
  static const kPatientsAge = const RetainDeviceIdentificationOption(0x00101010, "PatientsAge", null);
  static const kPatientsBirthDate = const RetainDeviceIdentificationOption(0x00100030, "PatientsBirthDate", null);
  static const kPatientsBirthName = const RetainDeviceIdentificationOption(0x00101005, "PatientsBirthName", null);
  static const kPatientsBirthTime = const RetainDeviceIdentificationOption(0x00100032, "PatientsBirthTime", null);
  static const kPatientsInstitutionResidence = const RetainDeviceIdentificationOption(0x00380400, "PatientsInstitutionResidence", null);
  static const kPatientsInsurancePlanCodeSequence = const RetainDeviceIdentificationOption(0x00100050, "PatientsInsurancePlanCodeSequence", null);
  static const kPatientsMothersBirthName = const RetainDeviceIdentificationOption(0x00101060, "PatientsMothersBirthName", null);
  static const kPatientsName = const RetainDeviceIdentificationOption(0x00100010, "PatientsName", null);
  static const kPatientsPrimaryLanguageCodeSequence = const RetainDeviceIdentificationOption(0x00100101, "PatientsPrimaryLanguageCodeSequence", null);
  static const kPatientsPrimaryLanguageModifierCodeSequence = const RetainDeviceIdentificationOption(0x00100102, "PatientsPrimaryLanguageModifierCodeSequence", null);
  static const kPatientsReligiousPreference = const RetainDeviceIdentificationOption(0x001021F0, "PatientsReligiousPreference", null);
  static const kPatientsSex = const RetainDeviceIdentificationOption(0x00100040, "PatientsSex", null);
  static const kPatientsSize = const RetainDeviceIdentificationOption(0x00101020, "PatientsSize", null);
  static const kPatientsTelephoneNumbers = const RetainDeviceIdentificationOption(0x00102154, "PatientsTelephoneNumbers", null);
  static const kPatientsWeight = const RetainDeviceIdentificationOption(0x00101030, "PatientsWeight", null);
  static const kPerformedLocation = const RetainDeviceIdentificationOption(0x00400243, "PerformedLocation", null);
  static const kPerformedProcedureStepDescription = const RetainDeviceIdentificationOption(0x00400254, "PerformedProcedureStepDescription", null);
  static const kPerformedProcedureStepEndDate = const RetainDeviceIdentificationOption(0x00400250, "PerformedProcedureStepEndDate", null);
  static const kPerformedProcedureStepEndTime = const RetainDeviceIdentificationOption(0x00400251, "PerformedProcedureStepEndTime", null);
  static const kPerformedProcedureStepID = const RetainDeviceIdentificationOption(0x00400253, "PerformedProcedureStepID", null);
  static const kPerformedProcedureStepStartDate = const RetainDeviceIdentificationOption(0x00400244, "PerformedProcedureStepStartDate", null);
  static const kPerformedProcedureStepStartTime = const RetainDeviceIdentificationOption(0x00400245, "PerformedProcedureStepStartTime", null);
  static const kPerformedStationAETitle = const RetainDeviceIdentificationOption(0x00400241, "PerformedStationAETitle", Action.K);
  static const kPerformedStationGeographicLocationCodeSequence = const RetainDeviceIdentificationOption(0x00404030, "PerformedStationGeographicLocationCodeSequence", Action.K);
  static const kPerformedStationName = const RetainDeviceIdentificationOption(0x00400242, "PerformedStationName", Action.K);
  static const kPerformedStationNameCodeSequence = const RetainDeviceIdentificationOption(0x00404028, "PerformedStationNameCodeSequence", Action.K);
  static const kPerformingPhysicianIdentificationSequence = const RetainDeviceIdentificationOption(0x00081052, "PerformingPhysicianIdentificationSequence", null);
  static const kPerformingPhysiciansName = const RetainDeviceIdentificationOption(0x00081050, "PerformingPhysiciansName", null);
  static const kPersonAddress = const RetainDeviceIdentificationOption(0x00401102, "PersonAddress", null);
  static const kPersonIdentificationCodeSequence = const RetainDeviceIdentificationOption(0x00401101, "PersonIdentificationCodeSequence", null);
  static const kPersonName = const RetainDeviceIdentificationOption(0x0040A123, "PersonName", null);
  static const kPersonTelephoneNumbers = const RetainDeviceIdentificationOption(0x00401103, "PersonTelephoneNumbers", null);
  static const kPhysicianApprovingInterpretation = const RetainDeviceIdentificationOption(0x40080114, "PhysicianApprovingInterpretation", null);
  static const kPhysician0xsReadingStudyIdentificationSequence = const RetainDeviceIdentificationOption(0x00081062, "Physician0xsReadingStudyIdentificationSequence", null);
  static const kPhysician0xsofRecord = const RetainDeviceIdentificationOption(0x00081048, "Physician0xsofRecord", null);
  static const kPhysician0xsofRecordIdentificationSequence = const RetainDeviceIdentificationOption(0x00081049, "Physician0xsofRecordIdentificationSequence", null);
  static const kPlacerOrderNumber_ImagingServiceRequest = const RetainDeviceIdentificationOption(0x00402016, "PlacerOrderNumber_ImagingServiceRequest", null);
  static const kPlateID = const RetainDeviceIdentificationOption(0x00181004, "PlateID", Action.K);
  static const kPre_Medication = const RetainDeviceIdentificationOption(0x00400012, "Pre_Medication", null);
  static const kPregnancyStatus = const RetainDeviceIdentificationOption(0x001021C0, "PregnancyStatus", null);
  static const kProtocolName = const RetainDeviceIdentificationOption(0x00181030, "ProtocolName", null);
  static const kReasonfortheImagingServiceRequest = const RetainDeviceIdentificationOption(0x00402001, "ReasonfortheImagingServiceRequest", null);
  static const kReasonforStudy = const RetainDeviceIdentificationOption(0x00321030, "ReasonforStudy", null);
  static const kReferencedDigitalSignatureSequence = const RetainDeviceIdentificationOption(0x04000402, "ReferencedDigitalSignatureSequence", null);
  static const kReferencedFrameofReferenceUID = const RetainDeviceIdentificationOption(0x30060024, "ReferencedFrameofReferenceUID", null);
  static const kReferencedGeneralPurposeScheduledProcedureStepTransactionUID = const RetainDeviceIdentificationOption(0x00404023, "ReferencedGeneralPurposeScheduledProcedureStepTransactionUID", null);
  static const kReferencedImageSequence = const RetainDeviceIdentificationOption(0x00081140, "ReferencedImageSequence", null);
  static const kReferencedPatientAliasSequence = const RetainDeviceIdentificationOption(0x00380004, "ReferencedPatientAliasSequence", null);
  static const kReferencedPatientSequence = const RetainDeviceIdentificationOption(0x00081120, "ReferencedPatientSequence", null);
  static const kReferencedPerformedProcedureStepSequence = const RetainDeviceIdentificationOption(0x00081111, "ReferencedPerformedProcedureStepSequence", null);
  static const kReferencedSOPInstanceMACSequence = const RetainDeviceIdentificationOption(0x04000403, "ReferencedSOPInstanceMACSequence", null);
  static const kReferencedSOPInstanceUID = const RetainDeviceIdentificationOption(0x00081155, "ReferencedSOPInstanceUID", null);
  static const kReferencedSOPInstanceUIDinFile = const RetainDeviceIdentificationOption(0x00041511, "ReferencedSOPInstanceUIDinFile", null);
  static const kReferencedStudySequence = const RetainDeviceIdentificationOption(0x00081110, "ReferencedStudySequence", null);
  static const kReferringPhysiciansAddress = const RetainDeviceIdentificationOption(0x00080092, "ReferringPhysiciansAddress", null);
  static const kReferringPhysiciansIdentificationSequence = const RetainDeviceIdentificationOption(0x00080096, "ReferringPhysiciansIdentificationSequence", null);
  static const kReferringPhysiciansName = const RetainDeviceIdentificationOption(0x00080090, "ReferringPhysiciansName", null);
  static const kReferringPhysiciansTelephoneNumbers = const RetainDeviceIdentificationOption(0x00080094, "ReferringPhysiciansTelephoneNumbers", null);
  static const kRegionofResidence = const RetainDeviceIdentificationOption(0x00102152, "RegionofResidence", null);
  static const kRelatedFrameofReferenceUID = const RetainDeviceIdentificationOption(0x300600C2, "RelatedFrameofReferenceUID", null);
  static const kRequestAttributesSequence = const RetainDeviceIdentificationOption(0x00400275, "RequestAttributesSequence", null);
  static const kRequestedContrastAgent = const RetainDeviceIdentificationOption(0x00321070, "RequestedContrastAgent", null);
  static const kRequestedProcedureComments = const RetainDeviceIdentificationOption(0x00401400, "RequestedProcedureComments", null);
  static const kRequestedProcedureDescription = const RetainDeviceIdentificationOption(0x00321060, "RequestedProcedureDescription", null);
  static const kRequestedProcedureID = const RetainDeviceIdentificationOption(0x00401001, "RequestedProcedureID", null);
  static const kRequestedProcedureLocation = const RetainDeviceIdentificationOption(0x00401005, "RequestedProcedureLocation", null);
  static const kRequestedSOPInstanceUID = const RetainDeviceIdentificationOption(0x00001001, "RequestedSOPInstanceUID", null);
  static const kRequestingPhysician = const RetainDeviceIdentificationOption(0x00321032, "RequestingPhysician", null);
  static const kRequestingService = const RetainDeviceIdentificationOption(0x00321033, "RequestingService", null);
  static const kResponsibleOrganization = const RetainDeviceIdentificationOption(0x00102299, "ResponsibleOrganization", null);
  static const kResponsiblePerson = const RetainDeviceIdentificationOption(0x00102297, "ResponsiblePerson", null);
  static const kResultsComments = const RetainDeviceIdentificationOption(0x40084000, "ResultsComments", null);
  static const kResultsDistributionListSequence = const RetainDeviceIdentificationOption(0x40080118, "ResultsDistributionListSequence", null);
  static const kResultsIDIssuer = const RetainDeviceIdentificationOption(0x40080042, "ResultsIDIssuer", null);
  static const kReviewerName = const RetainDeviceIdentificationOption(0x300E0008, "ReviewerName", null);
  static const kScheduledHumanPerformersSequence = const RetainDeviceIdentificationOption(0x00404034, "ScheduledHumanPerformersSequence", null);
  static const kScheduledPatientInstitutionResidence = const RetainDeviceIdentificationOption(0x0038001E, "ScheduledPatientInstitutionResidence", null);
  static const kScheduledPerformingPhysicianIdentificationSequence = const RetainDeviceIdentificationOption(0x0040000B, "ScheduledPerformingPhysicianIdentificationSequence", null);
  static const kScheduledPerformingPhysicianName = const RetainDeviceIdentificationOption(0x00400006, "ScheduledPerformingPhysicianName", null);
  static const kScheduledProcedureStepEndDate = const RetainDeviceIdentificationOption(0x00400004, "ScheduledProcedureStepEndDate", null);
  static const kScheduledProcedureStepEndTime = const RetainDeviceIdentificationOption(0x00400005, "ScheduledProcedureStepEndTime", null);
  static const kScheduledProcedureStepDescription = const RetainDeviceIdentificationOption(0x00400007, "ScheduledProcedureStepDescription", null);
  static const kScheduledProcedureStepLocation = const RetainDeviceIdentificationOption(0x00400011, "ScheduledProcedureStepLocation", Action.K);
  static const kScheduledProcedureStepStartDate = const RetainDeviceIdentificationOption(0x00400002, "ScheduledProcedureStepStartDate", null);
  static const kScheduledProcedureStepStartTime = const RetainDeviceIdentificationOption(0x00400003, "ScheduledProcedureStepStartTime", null);
  static const kScheduledStationAETitle = const RetainDeviceIdentificationOption(0x00400001, "ScheduledStationAETitle", Action.K);
  static const kScheduledStationGeographicLocationCodeSequence = const RetainDeviceIdentificationOption(0x00404027, "ScheduledStationGeographicLocationCodeSequence", Action.K);
  static const kScheduledStationName = const RetainDeviceIdentificationOption(0x00400010, "ScheduledStationName", Action.K);
  static const kScheduledStationNameCodeSequence = const RetainDeviceIdentificationOption(0x00404025, "ScheduledStationNameCodeSequence", Action.K);
  static const kScheduledStudyLocation = const RetainDeviceIdentificationOption(0x00321020, "ScheduledStudyLocation", Action.K);
  static const kScheduledStudyLocationAETitle = const RetainDeviceIdentificationOption(0x00321021, "ScheduledStudyLocationAETitle", Action.K);
  static const kSeriesDate = const RetainDeviceIdentificationOption(0x00080021, "SeriesDate", null);
  static const kSeriesDescription = const RetainDeviceIdentificationOption(0x0008103E, "SeriesDescription", null);
  static const kSeriesInstanceUID = const RetainDeviceIdentificationOption(0x0020000E, "SeriesInstanceUID", null);
  static const kSeriesTime = const RetainDeviceIdentificationOption(0x00080031, "SeriesTime", null);
  static const kServiceEpisodeDescription = const RetainDeviceIdentificationOption(0x00380062, "ServiceEpisodeDescription", null);
  static const kServiceEpisodeID = const RetainDeviceIdentificationOption(0x00380060, "ServiceEpisodeID", null);
  static const kSmokingStatus = const RetainDeviceIdentificationOption(0x001021A0, "SmokingStatus", null);
  static const kSOPInstanceUID = const RetainDeviceIdentificationOption(0x00080018, "SOPInstanceUID", null);
  static const kSourceImageSequence = const RetainDeviceIdentificationOption(0x00082112, "SourceImageSequence", null);
  static const kSpecialNeeds = const RetainDeviceIdentificationOption(0x00380050, "SpecialNeeds", null);
  static const kStationName = const RetainDeviceIdentificationOption(0x00081010, "StationName", Action.K);
  static const kStorageMediaFile_setUID = const RetainDeviceIdentificationOption(0x00880140, "StorageMediaFile_setUID", null);
  static const kStudyComments = const RetainDeviceIdentificationOption(0x00324000, "StudyComments", null);
  static const kStudyDate = const RetainDeviceIdentificationOption(0x00080020, "StudyDate", null);
  static const kStudyDescription = const RetainDeviceIdentificationOption(0x00081030, "StudyDescription", null);
  static const kStudyID = const RetainDeviceIdentificationOption(0x00200010, "StudyID", null);
  static const kStudyIDIssuer = const RetainDeviceIdentificationOption(0x00320012, "StudyIDIssuer", null);
  static const kStudyInstanceUID = const RetainDeviceIdentificationOption(0x0020000D, "StudyInstanceUID", null);
  static const kStudyTime = const RetainDeviceIdentificationOption(0x00080030, "StudyTime", null);
  static const kSynchronizationFrameofReferenceUID = const RetainDeviceIdentificationOption(0x00200200, "SynchronizationFrameofReferenceUID", null);
  static const kTemplateExtensionCreatorUID = const RetainDeviceIdentificationOption(0x0040DB0D, "TemplateExtensionCreatorUID", null);
  static const kTemplateExtensionOrganizationUID = const RetainDeviceIdentificationOption(0x0040DB0C, "TemplateExtensionOrganizationUID", null);
  static const kTextComments = const RetainDeviceIdentificationOption(0x40004000, "TextComments", null);
  static const kTextString = const RetainDeviceIdentificationOption(0x20300020, "TextString", null);
  static const kTimezoneOffsetFromUTC = const RetainDeviceIdentificationOption(0x00080201, "TimezoneOffsetFromUTC", null);
  static const kTopicAuthor = const RetainDeviceIdentificationOption(0x00880910, "TopicAuthor", null);
  static const kTopicKeywords = const RetainDeviceIdentificationOption(0x00880912, "TopicKeywords", null);
  static const kTopicSubject = const RetainDeviceIdentificationOption(0x00880906, "TopicSubject", null);
  static const kTopicTitle = const RetainDeviceIdentificationOption(0x00880904, "TopicTitle", null);
  static const kTransactionUID = const RetainDeviceIdentificationOption(0x00081195, "TransactionUID", null);
  static const kUID = const RetainDeviceIdentificationOption(0x0040A124, "UID", null);
  static const kVerifyingObserverIdentificationCodeSequence = const RetainDeviceIdentificationOption(0x0040A088, "VerifyingObserverIdentificationCodeSequence", null);
  static const kVerifyingObserverName = const RetainDeviceIdentificationOption(0x0040A075, "VerifyingObserverName", null);
  static const kVerifyingObserverSequence = const RetainDeviceIdentificationOption(0x0040A073, "VerifyingObserverSequence", null);
  static const kVerifyingOrganization = const RetainDeviceIdentificationOption(0x0040A027, "VerifyingOrganization", null);
  static const kVisitComments = const RetainDeviceIdentificationOption(0x00384000, "VisitComments", null);


  static const Map<int, RetainDeviceIdentificationOption> tagToRetainDeviceIdentification = const {
    0x00080050: kAccessionNumber,
    0x00184000: kAcquisitionComments,
    0x00400555: kAcquisitionContextSequence,
    0x00080022: kAcquisitionDate,
    0x0008002A: kAcquisitionDateTime,
    0x00181400: kAcquisitionDeviceProcessingDescription,
    0x00189424: kAcquisitionProtocolDescription,
    0x00080032: kAcquisitionTime,
    0x00404035: kActualHumanPerformersSequence,
    0x001021B0: kAdditionalPatientsHistory,
    0x00380010: kAdmissionID,
    0x00380020: kAdmittingDate,
    0x00081084: kAdmittingDiagnosesCodeSequence,
    0x00081080: kAdmittingDiagnosesDescription,
    0x00380021: kAdmittingTime,
    0x00001000: kAffectedSOPInstanceUID,
    0x00102110: kAllergies,
    0x40000010: kArbitrary,
    0x0040A078: kAuthorObserverSequence,
    0x00101081: kBranchofService,
    0x00181007: kCassetteID,
    0x00400280: kCommentsonthePerformedProcedureStep,
    0x00209161: kConcatenationUID,
    0x00403001: kConfidentialityConstraintonPatientDataDescription,
    0x00700084: kContentCreatorsName,
    0x00700086: kContentCreatorsIdentificationCodeSequence,
    0x00080023: kContentDate,
    0x0040A730: kContentSequence,
    0x00080033: kContentTime,
    0x0008010D: kContextGroupExtensionCreatorUID,
    0x00180010: kContrastBolusAgent,
    0x0018A003: kContributionDescription,
    0x00102150: kCountryofResidence,
    0x00089123: kCreatorVersionUID,
    0x00380300: kCurrentPatientLocation,
    0x00080025: kCurveDate,
    0x00080035: kCurveTime,
    0x0040A07C: kCustodialOrganizationSequence,
    0xFFFCFFFC: kDataSetTrailingPadding,
    0x00082111: kDerivationDescription,
    0x0018700A: kDetectorID,
    0x00181000: kDeviceSerialNumber,
    0x00181002: kDeviceUID,
    0x04000100: kDigitalSignatureUID,
    0xFFFAFFFA: kDigitalSignaturesSequence,
    0x00209164: kDimensionOrganizationUID,
    0x00380040: kDischargeDiagnosisDescription,
    0x4008011A: kDistributionAddress,
    0x40080119: kDistributionName,
    0x300A0013: kDoseReferenceUID,
    0x00102160: kEthnicGroup,
    0x00080058: kFailedSOPInstanceUIDList,
    0x0070031A: kFiducialUID,
    0x00402017: kFillerOrderNumber_ImagingServiceRequest,
    0x00209158: kFrameComments,
    0x00200052: kFrameofReferenceUID,
    0x00181008: kGantryID,
    0x00181005: kGeneratorID,
    0x00700001: kGraphicAnnotationSequence,
    0x00404037: kHumanPerformersName,
    0x00404036: kHumanPerformersOrganization,
    0x00880200: kIconImageSequence0xseeNote12,
    0x00084000: kIdentifyingComments,
    0x00204000: kImageComments,
    0x00284000: kImagePresentationComments,
    0x00402400: kImagingServiceRequestComments,
    0x40080300: kImpressions,
    0x00080014: kInstanceCreatorUID,
    0x00080081: kInstitutionAddress,
    0x00080082: kInstitutionCodeSequence,
    0x00080080: kInstitutionName,
    0x00081040: kInstitutionalDepartmentName,
    0x00101050: kInsurancePlanIdentification,
    0x00401011: kIntendedRecipientsofResultsIdentificationSequence,
    0x40080111: kInterpretationApproverSequence,
    0x4008010C: kInterpretationAuthor,
    0x40080115: kInterpretationDiagnosisDescription,
    0x40080202: kInterpretationIDIssuer,
    0x40080102: kInterpretationRecorder,
    0x4008010B: kInterpretationText,
    0x4008010A: kInterpretationTranscriber,
    0x00083010: kIrradiationEventUID,
    0x00380011: kIssuerofAdmissionID,
    0x00100021: kIssuerofPatientID,
    0x00380061: kIssuerofServiceEpisodeID,
    0x00281214: kLargePaletteColorLookupTableUID,
    0x001021D0: kLastMenstrualDate,
    0x04000404: kMAC,
    0x00020003: kMediaStorageSOPInstanceUID,
    0x00102000: kMedicalAlerts,
    0x00101090: kMedicalRecordLocator,
    0x00101080: kMilitaryRank,
    0x04000550: kModifiedAttributesSequence,
    0x00203406: kModifiedImageDescription,
    0x00203401: kModifyingDeviceID,
    0x00203404: kModifyingDeviceManufacturer,
    0x00081060: kNameofPhysician0xsReadingStudy,
    0x00401010: kNamesofIntendedRecipientofResults,
    0x00102180: kOccupation,
    0x00081072: kOperatorsIdentificationSequence,
    0x00081070: kOperatorsName,
    0x04000561: kOriginalAttributesSequence,
    0x00402010: kOrderCallbackPhoneNumber,
    0x00402008: kOrderEnteredBy,
    0x00402009: kOrderEntererLocation,
    0x00101000: kOtherPatientIDs,
    0x00101002: kOtherPatientIDsSequence,
    0x00101001: kOtherPatientNames,
    0x00080024: kOverlayDate,
    0x00080034: kOverlayTime,
    0x00281199: kPaletteColorLookupTableUID,
    0x0040A07A: kParticipantSequence,
    0x00101040: kPatientAddress,
    0x00104000: kPatientComments,
    0x00100020: kPatientID,
    0x00102203: kPatientSexNeutered,
    0x00380500: kPatientState,
    0x00401004: kPatientTransportArrangements,
    0x00101010: kPatientsAge,
    0x00100030: kPatientsBirthDate,
    0x00101005: kPatientsBirthName,
    0x00100032: kPatientsBirthTime,
    0x00380400: kPatientsInstitutionResidence,
    0x00100050: kPatientsInsurancePlanCodeSequence,
    0x00101060: kPatientsMothersBirthName,
    0x00100010: kPatientsName,
    0x00100101: kPatientsPrimaryLanguageCodeSequence,
    0x00100102: kPatientsPrimaryLanguageModifierCodeSequence,
    0x001021F0: kPatientsReligiousPreference,
    0x00100040: kPatientsSex,
    0x00101020: kPatientsSize,
    0x00102154: kPatientsTelephoneNumbers,
    0x00101030: kPatientsWeight,
    0x00400243: kPerformedLocation,
    0x00400254: kPerformedProcedureStepDescription,
    0x00400250: kPerformedProcedureStepEndDate,
    0x00400251: kPerformedProcedureStepEndTime,
    0x00400253: kPerformedProcedureStepID,
    0x00400244: kPerformedProcedureStepStartDate,
    0x00400245: kPerformedProcedureStepStartTime,
    0x00400241: kPerformedStationAETitle,
    0x00404030: kPerformedStationGeographicLocationCodeSequence,
    0x00400242: kPerformedStationName,
    0x00404028: kPerformedStationNameCodeSequence,
    0x00081052: kPerformingPhysicianIdentificationSequence,
    0x00081050: kPerformingPhysiciansName,
    0x00401102: kPersonAddress,
    0x00401101: kPersonIdentificationCodeSequence,
    0x0040A123: kPersonName,
    0x00401103: kPersonTelephoneNumbers,
    0x40080114: kPhysicianApprovingInterpretation,
    0x00081062: kPhysician0xsReadingStudyIdentificationSequence,
    0x00081048: kPhysician0xsofRecord,
    0x00081049: kPhysician0xsofRecordIdentificationSequence,
    0x00402016: kPlacerOrderNumber_ImagingServiceRequest,
    0x00181004: kPlateID,
    0x00400012: kPre_Medication,
    0x001021C0: kPregnancyStatus,
    0x00181030: kProtocolName,
    0x00402001: kReasonfortheImagingServiceRequest,
    0x00321030: kReasonforStudy,
    0x04000402: kReferencedDigitalSignatureSequence,
    0x30060024: kReferencedFrameofReferenceUID,
    0x00404023: kReferencedGeneralPurposeScheduledProcedureStepTransactionUID,
    0x00081140: kReferencedImageSequence,
    0x00380004: kReferencedPatientAliasSequence,
    0x00081120: kReferencedPatientSequence,
    0x00081111: kReferencedPerformedProcedureStepSequence,
    0x04000403: kReferencedSOPInstanceMACSequence,
    0x00081155: kReferencedSOPInstanceUID,
    0x00041511: kReferencedSOPInstanceUIDinFile,
    0x00081110: kReferencedStudySequence,
    0x00080092: kReferringPhysiciansAddress,
    0x00080096: kReferringPhysiciansIdentificationSequence,
    0x00080090: kReferringPhysiciansName,
    0x00080094: kReferringPhysiciansTelephoneNumbers,
    0x00102152: kRegionofResidence,
    0x300600C2: kRelatedFrameofReferenceUID,
    0x00400275: kRequestAttributesSequence,
    0x00321070: kRequestedContrastAgent,
    0x00401400: kRequestedProcedureComments,
    0x00321060: kRequestedProcedureDescription,
    0x00401001: kRequestedProcedureID,
    0x00401005: kRequestedProcedureLocation,
    0x00001001: kRequestedSOPInstanceUID,
    0x00321032: kRequestingPhysician,
    0x00321033: kRequestingService,
    0x00102299: kResponsibleOrganization,
    0x00102297: kResponsiblePerson,
    0x40084000: kResultsComments,
    0x40080118: kResultsDistributionListSequence,
    0x40080042: kResultsIDIssuer,
    0x300E0008: kReviewerName,
    0x00404034: kScheduledHumanPerformersSequence,
    0x0038001E: kScheduledPatientInstitutionResidence,
    0x0040000B: kScheduledPerformingPhysicianIdentificationSequence,
    0x00400006: kScheduledPerformingPhysicianName,
    0x00400004: kScheduledProcedureStepEndDate,
    0x00400005: kScheduledProcedureStepEndTime,
    0x00400007: kScheduledProcedureStepDescription,
    0x00400011: kScheduledProcedureStepLocation,
    0x00400002: kScheduledProcedureStepStartDate,
    0x00400003: kScheduledProcedureStepStartTime,
    0x00400001: kScheduledStationAETitle,
    0x00404027: kScheduledStationGeographicLocationCodeSequence,
    0x00400010: kScheduledStationName,
    0x00404025: kScheduledStationNameCodeSequence,
    0x00321020: kScheduledStudyLocation,
    0x00321021: kScheduledStudyLocationAETitle,
    0x00080021: kSeriesDate,
    0x0008103E: kSeriesDescription,
    0x0020000E: kSeriesInstanceUID,
    0x00080031: kSeriesTime,
    0x00380062: kServiceEpisodeDescription,
    0x00380060: kServiceEpisodeID,
    0x001021A0: kSmokingStatus,
    0x00080018: kSOPInstanceUID,
    0x00082112: kSourceImageSequence,
    0x00380050: kSpecialNeeds,
    0x00081010: kStationName,
    0x00880140: kStorageMediaFile_setUID,
    0x00324000: kStudyComments,
    0x00080020: kStudyDate,
    0x00081030: kStudyDescription,
    0x00200010: kStudyID,
    0x00320012: kStudyIDIssuer,
    0x0020000D: kStudyInstanceUID,
    0x00080030: kStudyTime,
    0x00200200: kSynchronizationFrameofReferenceUID,
    0x0040DB0D: kTemplateExtensionCreatorUID,
    0x0040DB0C: kTemplateExtensionOrganizationUID,
    0x40004000: kTextComments,
    0x20300020: kTextString,
    0x00080201: kTimezoneOffsetFromUTC,
    0x00880910: kTopicAuthor,
    0x00880912: kTopicKeywords,
    0x00880906: kTopicSubject,
    0x00880904: kTopicTitle,
    0x00081195: kTransactionUID,
    0x0040A124: kUID,
    0x0040A088: kVerifyingObserverIdentificationCodeSequence,
    0x0040A075: kVerifyingObserverName,
    0x0040A073: kVerifyingObserverSequence,
    0x0040A027: kVerifyingOrganization,
    0x00384000: kVisitComments,
  };


}
  