// Copyright (c) 2016, Open DICOMweb Project. All rights reserved.
// Use of this source code is governed by the open source license
// that can be found in the LICENSE file.
// Author: Jim Philbin <jfphilbin@gmail.edu> -
// See the AUTHORS file for other contributors.

// *** This file generated by '../bin/generate/generate_basic_profile.dart' ***
// ----------------------------------------------------------

import 'package:deid/src/deid/action.dart';

class RetainLongModifDatesOption {
  final int tag;
  final String keyword;
  final Action action;

  const RetainLongModifDatesOption(this.tag, this.keyword, this.action);

  static lookup(int tag) => map[tag];

  static const kAcquisitionDate = const RetainLongModifDatesOption(0x00080022, "AcquisitionDate", Action.C);
  static const kAcquisitionDateTime = const RetainLongModifDatesOption(0x0008002A, "AcquisitionDateTime", Action.C);
  static const kAcquisitionTime = const RetainLongModifDatesOption(0x00080032, "AcquisitionTime", Action.C);
  static const kAdmittingDate = const RetainLongModifDatesOption(0x00380020, "AdmittingDate", Action.C);
  static const kAdmittingTime = const RetainLongModifDatesOption(0x00380021, "AdmittingTime", Action.C);
  static const kContentDate = const RetainLongModifDatesOption(0x00080023, "ContentDate", Action.C);
  static const kContentTime = const RetainLongModifDatesOption(0x00080033, "ContentTime", Action.C);
  static const kCurveDate = const RetainLongModifDatesOption(0x00080025, "CurveDate", Action.C);
  static const kCurveTime = const RetainLongModifDatesOption(0x00080035, "CurveTime", Action.C);
  static const kLastMenstrualDate = const RetainLongModifDatesOption(0x001021D0, "LastMenstrualDate", Action.C);
  static const kOverlayDate = const RetainLongModifDatesOption(0x00080024, "OverlayDate", Action.C);
  static const kOverlayTime = const RetainLongModifDatesOption(0x00080034, "OverlayTime", Action.C);
  static const kPerformedProcedureStepEndDate = const RetainLongModifDatesOption(0x00400250, "PerformedProcedureStepEndDate", Action.C);
  static const kPerformedProcedureStepEndTime = const RetainLongModifDatesOption(0x00400251, "PerformedProcedureStepEndTime", Action.C);
  static const kPerformedProcedureStepStartDate = const RetainLongModifDatesOption(0x00400244, "PerformedProcedureStepStartDate", Action.C);
  static const kPerformedProcedureStepStartTime = const RetainLongModifDatesOption(0x00400245, "PerformedProcedureStepStartTime", Action.C);
  static const kScheduledProcedureStepEndDate = const RetainLongModifDatesOption(0x00400004, "ScheduledProcedureStepEndDate", Action.C);
  static const kScheduledProcedureStepEndTime = const RetainLongModifDatesOption(0x00400005, "ScheduledProcedureStepEndTime", Action.C);
  static const kScheduledProcedureStepStartDate = const RetainLongModifDatesOption(0x00400002, "ScheduledProcedureStepStartDate", Action.C);
  static const kScheduledProcedureStepStartTime = const RetainLongModifDatesOption(0x00400003, "ScheduledProcedureStepStartTime", Action.C);
  static const kSeriesDate = const RetainLongModifDatesOption(0x00080021, "SeriesDate", Action.C);
  static const kSeriesTime = const RetainLongModifDatesOption(0x00080031, "SeriesTime", Action.C);
  static const kStudyDate = const RetainLongModifDatesOption(0x00080020, "StudyDate", Action.C);
  static const kStudyTime = const RetainLongModifDatesOption(0x00080030, "StudyTime", Action.C);
  static const kTimezoneOffsetFromUTC = const RetainLongModifDatesOption(0x00080201, "TimezoneOffsetFromUTC", Action.C);


  static const Map<int, String> map = const {
    0x00080022: kAcquisitionDate,
    0x0008002A: kAcquisitionDateTime,
    0x00080032: kAcquisitionTime,
    0x00380020: kAdmittingDate,
    0x00380021: kAdmittingTime,
    0x00080023: kContentDate,
    0x00080033: kContentTime,
    0x00080025: kCurveDate,
    0x00080035: kCurveTime,
    0x001021D0: kLastMenstrualDate,
    0x00080024: kOverlayDate,
    0x00080034: kOverlayTime,
    0x00400250: kPerformedProcedureStepEndDate,
    0x00400251: kPerformedProcedureStepEndTime,
    0x00400244: kPerformedProcedureStepStartDate,
    0x00400245: kPerformedProcedureStepStartTime,
    0x00400004: kScheduledProcedureStepEndDate,
    0x00400005: kScheduledProcedureStepEndTime,
    0x00400002: kScheduledProcedureStepStartDate,
    0x00400003: kScheduledProcedureStepStartTime,
    0x00080021: kSeriesDate,
    0x00080031: kSeriesTime,
    0x00080020: kStudyDate,
    0x00080030: kStudyTime,
    0x00080201: kTimezoneOffsetFromUTC};

  static const List<int> keys = const [
    0x00080022,
    0x0008002A,
    0x00080032,
    0x00380020,
    0x00380021,
    0x00080023,
    0x00080033,
    0x00080025,
    0x00080035,
    0x001021D0,
    0x00080024,
    0x00080034,
    0x00400250,
    0x00400251,
    0x00400244,
    0x00400245,
    0x00400004,
    0x00400005,
    0x00400002,
    0x00400003,
    0x00080021,
    0x00080031,
    0x00080020,
    0x00080030,
    0x00080201];

  static const List<String> values = const [
    kAcquisitionDate,
    kAcquisitionDateTime,
    kAcquisitionTime,
    kAdmittingDate,
    kAdmittingTime,
    kContentDate,
    kContentTime,
    kCurveDate,
    kCurveTime,
    kLastMenstrualDate,
    kOverlayDate,
    kOverlayTime,
    kPerformedProcedureStepEndDate,
    kPerformedProcedureStepEndTime,
    kPerformedProcedureStepStartDate,
    kPerformedProcedureStepStartTime,
    kScheduledProcedureStepEndDate,
    kScheduledProcedureStepEndTime,
    kScheduledProcedureStepStartDate,
    kScheduledProcedureStepStartTime,
    kSeriesDate,
    kSeriesTime,
    kStudyDate,
    kStudyTime,
    kTimezoneOffsetFromUTC];



}
  