// Copyright (c) 2016, Open DICOMweb Project. All rights reserved.
// Use of this source code is governed by the open source license
// that can be found in the LICENSE file.
// Author: Jim Philbin <jfphilbin@gmail.edu> -
// See the AUTHORS file for other contributors.

// *** This file generated by '../bin/generate/generate_basic_profile.dart' ***
// ----------------------------------------------------------

import 'package:deid/src/deid/action.dart';

class RetainPatientCharacteristicsOption {
  final int tag;
  final String keyword;
  final Action action;

  const RetainPatientCharacteristicsOption(this.tag, this.keyword, this.action);

  static lookup(int tag) => map[tag];

  static const kAllergies = const RetainPatientCharacteristicsOption(0x00102110, "Allergies", Action.C);
  static const kEthnicGroup = const RetainPatientCharacteristicsOption(0x00102160, "EthnicGroup", Action.K);
  static const kPatientSexNeutered = const RetainPatientCharacteristicsOption(0x00102203, "PatientSexNeutered", Action.K);
  static const kPatientState = const RetainPatientCharacteristicsOption(0x00380500, "PatientState", Action.C);
  static const kPatientsAge = const RetainPatientCharacteristicsOption(0x00101010, "PatientsAge", Action.K);
  static const kPatientsSex = const RetainPatientCharacteristicsOption(0x00100040, "PatientsSex", Action.K);
  static const kPatientsSize = const RetainPatientCharacteristicsOption(0x00101020, "PatientsSize", Action.K);
  static const kPatientsWeight = const RetainPatientCharacteristicsOption(0x00101030, "PatientsWeight", Action.K);
  static const kPre_Medication = const RetainPatientCharacteristicsOption(0x00400012, "Pre_Medication", Action.C);
  static const kPregnancyStatus = const RetainPatientCharacteristicsOption(0x001021C0, "PregnancyStatus", Action.K);
  static const kSmokingStatus = const RetainPatientCharacteristicsOption(0x001021A0, "SmokingStatus", Action.K);
  static const kSpecialNeeds = const RetainPatientCharacteristicsOption(0x00380050, "SpecialNeeds", Action.C);


  static const Map<int, String> map = const {
    0x00102110: kAllergies,
    0x00102160: kEthnicGroup,
    0x00102203: kPatientSexNeutered,
    0x00380500: kPatientState,
    0x00101010: kPatientsAge,
    0x00100040: kPatientsSex,
    0x00101020: kPatientsSize,
    0x00101030: kPatientsWeight,
    0x00400012: kPre_Medication,
    0x001021C0: kPregnancyStatus,
    0x001021A0: kSmokingStatus,
    0x00380050: kSpecialNeeds};

  static const List<int> keys = const [
    0x00102110,
    0x00102160,
    0x00102203,
    0x00380500,
    0x00101010,
    0x00100040,
    0x00101020,
    0x00101030,
    0x00400012,
    0x001021C0,
    0x001021A0,
    0x00380050];

  static const List<String> values = const [
    kAllergies,
    kEthnicGroup,
    kPatientSexNeutered,
    kPatientState,
    kPatientsAge,
    kPatientsSex,
    kPatientsSize,
    kPatientsWeight,
    kPre_Medication,
    kPregnancyStatus,
    kSmokingStatus,
    kSpecialNeeds];



}
  