name: deidentification
version: 0.2.0
description: A library for de-identifying DICOM Studies.
author: Jim Philbin <jfphilbin@gmail.com>
description: DICOM De-Identification library
homepage: https://github.com/OpenDICOMweb/deidentification

dependencies:
  convert:
    path: C:/odw/sdk/convert
  core:
    path: C:/odw/sdk/core
  logger:
    path: C:/odw/sdk/logger
  path: '>= 1.3.9'

dev_dependencies:
  test: any
