name: deid
version: 0.5.4
description: A library for de-identifying DICOM Studies.
author: Jim Philbin <jfphilbin@gmail.com>
homepage: https://github.com/OpenDICOMweb/deid

sdk: ^1.24.2

dependencies:
  common:
    path: C:/odw/sdk/common
    version: ^0.5.6
  dictionary:
    path: C:/odw/sdk/dictionary
    version: ^0.5.6
  core:
    path: C:/odw/sdk/core
    version: 0.5.6
  dcm_convert:
    path: C:/odw/sdk/convert
    version: 0.5.6
  io:
    path: C:/odw/sdk/io
    version: ^0.5.4
  path: '>= 1.3.9'

dev_dependencies:
  coverage: "^0.7.3"
  dart_dev: "^1.0.0"
  dart_style: ">=0.1.8 <0.3.0"
  dartdoc: "^0.4.0"
  test: "^0.12.0"
