name: deid
version: 0.3.0
description: A library for de-identifying DICOM Studies.
author: Jim Philbin <jfphilbin@gmail.com>
description: DICOM De-Identification library
homepage: https://github.com/OpenDICOMweb/deid

dependencies:
  encode:
    path: C:/odw/sdk/encode
  core:
    path: C:/odw/sdk/core
  logger:
    path: C:/odw/sdk/logger
  io:
    path: C:/odw/sdk/io
  path: '>= 1.3.9'

dev_dependencies:
  test: any
