name: deid
version: 0.3.0
description: A library for de-identifying DICOM Studies.
author: Jim Philbin <jfphilbin@gmail.com>
description: DICOM De-Identification library
homepage: https://github.com/OpenDICOMweb/deid

sdk: ^1.21.0

dependencies:
  core:
    path: C:/odw/sdk/core
    version: 0.4.4
  encode:
    path: C:/odw/sdk/convert
  io:
    path: C:/odw/sdk/io
    version: ^
    version: 0.1.1
  path: '>= 1.3.9'

dev_dependencies:
  coverage: "^0.7.3"
  dart_dev: "^1.0.0"
  dart_style: ">=0.1.8 <0.3.0"
  dartdoc: "^0.4.0"
  test: "^0.12.0"
