name: deid
version: 0.6.0
description: A library for de-identifying DICOM Studies.
author: Jim Philbin <jfphilbin@gmail.com>
homepage: https://github.com/OpenDICOMweb/deid

sdk: ^1.24.2

dependencies:
  core:
    path: C:/odw/sdk/core
    version: 0.6.3
  dcm_convert:
    path: C:/odw/sdk/convert
    version: 0.6.3
  io:
    path: C:/odw/sdk/io
    version: ^0.6.0
  path: '>= 1.3.9'
  uid:
    path: C:/odw/sdk/uid
    version: ^0.6.1

dev_dependencies:
  coverage: "^0.7.3"
  dart_dev: "^1.0.0"
  dart_style: ">=0.1.8 <0.3.0"
  dartdoc: "^0.4.0"
  test: "^0.12.0"
