name: deid
version: 0.3.0
description: A library for de-identifying DICOM Studies.
author: Jim Philbin <jfphilbin@gmail.com>
description: DICOM De-Identification library
homepage: https://github.com/OpenDICOMweb/deid

dependencies:
  encode:
    path: C:/odw/sdk/convert
  core:
    path: C:/odw/sdk/core
    version: 0.4.1
  io:
    path: C:/odw/sdk/io
    version: 0.1.1
  path: '>= 1.3.9'

dev_dependencies:
  test: any
