name: deid
version: 0.1.1
description: A library for de-identifying DICOM Studies.
author: Jim Philbin <jfphilbin@gmail.com>
description: DICOM De-Identification library
homepage: https://github.com/OpenDICOMweb/deidentification

dependencies:
  core:
    path: C:/odw/sdk/core

dev_dependencies:
  test: any
