// Copyright (c) 2016, Open DICOMweb Project. All rights reserved.
// Use of this source code is governed by the open source license
// that can be found in the LICENSE file.
// Author: Jim Philbin <jfphilbin@gmail.edu> -
// See the AUTHORS file for other contributors.
library odw.sdk.deid.basic_profile;

// *** This file generated by '../deid/generate_basic_profile.dart' ***
// ----------------------------------------------------------

import 'package:deidentification/src/action.dart';

class BasicProfile {
  final int tag;
  final String keyword;
  final Action action;

  const BasicProfile(this.tag, this.keyword, this.action);

  static lookup(int tag) => tagToBasicProfile[tag];

  static const kAccessionNumber = const BasicProfile(0x00080050, "AccessionNumber", Action.Z);
  static const kAcquisitionComments = const BasicProfile(0x00184000, "AcquisitionComments", Action.X);
  static const kAcquisitionContextSequence = const BasicProfile(0x00400555, "AcquisitionContextSequence", Action.X);
  static const kAcquisitionDate = const BasicProfile(0x00080022, "AcquisitionDate", Action.XZ);
  static const kAcquisitionDateTime = const BasicProfile(0x0008002A, "AcquisitionDateTime", Action.XD);
  static const kAcquisitionDeviceProcessingDescription = const BasicProfile(0x00181400, "AcquisitionDeviceProcessingDescription", Action.XD);
  static const kAcquisitionProtocolDescription = const BasicProfile(0x00189424, "AcquisitionProtocolDescription", Action.X);
  static const kAcquisitionTime = const BasicProfile(0x00080032, "AcquisitionTime", Action.XZ);
  static const kActualHumanPerformersSequence = const BasicProfile(0x00404035, "ActualHumanPerformersSequence", Action.X);
  static const kAdditionalPatientsHistory = const BasicProfile(0x001021B0, "AdditionalPatientsHistory", Action.X);
  static const kAdmissionID = const BasicProfile(0x00380010, "AdmissionID", Action.X);
  static const kAdmittingDate = const BasicProfile(0x00380020, "AdmittingDate", Action.X);
  static const kAdmittingDiagnosesCodeSequence = const BasicProfile(0x00081084, "AdmittingDiagnosesCodeSequence", Action.X);
  static const kAdmittingDiagnosesDescription = const BasicProfile(0x00081080, "AdmittingDiagnosesDescription", Action.X);
  static const kAdmittingTime = const BasicProfile(0x00380021, "AdmittingTime", Action.X);
  static const kAffectedSOPInstanceUID = const BasicProfile(0x00001000, "AffectedSOPInstanceUID", Action.X);
  static const kAllergies = const BasicProfile(0x00102110, "Allergies", Action.X);
  static const kArbitrary = const BasicProfile(0x40000010, "Arbitrary", Action.X);
  static const kAuthorObserverSequence = const BasicProfile(0x0040A078, "AuthorObserverSequence", Action.X);
  static const kBranchofService = const BasicProfile(0x00101081, "BranchofService", Action.X);
  static const kCassetteID = const BasicProfile(0x00181007, "CassetteID", Action.X);
  static const kCommentsonthePerformedProcedureStep = const BasicProfile(0x00400280, "CommentsonthePerformedProcedureStep", Action.X);
  static const kConcatenationUID = const BasicProfile(0x00209161, "ConcatenationUID", Action.U);
  static const kConfidentialityConstraintonPatientDataDescription = const BasicProfile(0x00403001, "ConfidentialityConstraintonPatientDataDescription", Action.X);
  static const kContentCreatorsName = const BasicProfile(0x00700084, "ContentCreatorsName", Action.Z);
  static const kContentCreatorsIdentificationCodeSequence = const BasicProfile(0x00700086, "ContentCreatorsIdentificationCodeSequence", Action.X);
  static const kContentDate = const BasicProfile(0x00080023, "ContentDate", Action.ZD);
  static const kContentSequence = const BasicProfile(0x0040A730, "ContentSequence", Action.X);
  static const kContentTime = const BasicProfile(0x00080033, "ContentTime", Action.ZD);
  static const kContextGroupExtensionCreatorUID = const BasicProfile(0x0008010D, "ContextGroupExtensionCreatorUID", Action.U);
  static const kContrastBolusAgent = const BasicProfile(0x00180010, "ContrastBolusAgent", Action.ZD);
  static const kContributionDescription = const BasicProfile(0x0018A003, "ContributionDescription", Action.X);
  static const kCountryofResidence = const BasicProfile(0x00102150, "CountryofResidence", Action.X);
  static const kCreatorVersionUID = const BasicProfile(0x00089123, "CreatorVersionUID", Action.U);
  static const kCurrentPatientLocation = const BasicProfile(0x00380300, "CurrentPatientLocation", Action.X);
  static const kCurveData = const BasicProfile(0x50000000, "CurveData", Action.X);
  static const kCurveDate = const BasicProfile(0x00080025, "CurveDate", Action.X);
  static const kCurveTime = const BasicProfile(0x00080035, "CurveTime", Action.X);
  static const kCustodialOrganizationSequence = const BasicProfile(0x0040A07C, "CustodialOrganizationSequence", Action.X);
  static const kDataSetTrailingPadding = const BasicProfile(0xFFFCFFFC, "DataSetTrailingPadding", Action.X);
  static const kDerivationDescription = const BasicProfile(0x00082111, "DerivationDescription", Action.X);
  static const kDetectorID = const BasicProfile(0x0018700A, "DetectorID", Action.XD);
  static const kDeviceSerialNumber = const BasicProfile(0x00181000, "DeviceSerialNumber", Action.XZD);
  static const kDeviceUID = const BasicProfile(0x00181002, "DeviceUID", Action.U);
  static const kDigitalSignatureUID = const BasicProfile(0x04000100, "DigitalSignatureUID", Action.X);
  static const kDigitalSignaturesSequence = const BasicProfile(0xFFFAFFFA, "DigitalSignaturesSequence", Action.X);
  static const kDimensionOrganizationUID = const BasicProfile(0x00209164, "DimensionOrganizationUID", Action.U);
  static const kDischargeDiagnosisDescription = const BasicProfile(0x00380040, "DischargeDiagnosisDescription", Action.X);
  static const kDistributionAddress = const BasicProfile(0x4008011A, "DistributionAddress", Action.X);
  static const kDistributionName = const BasicProfile(0x40080119, "DistributionName", Action.X);
  static const kDoseReferenceUID = const BasicProfile(0x300A0013, "DoseReferenceUID", Action.U);
  static const kEthnicGroup = const BasicProfile(0x00102160, "EthnicGroup", Action.X);
  static const kFailedSOPInstanceUIDList = const BasicProfile(0x00080058, "FailedSOPInstanceUIDList", Action.U);
  static const kFiducialUID = const BasicProfile(0x0070031A, "FiducialUID", Action.U);
  static const kFillerOrderNumber_ImagingServiceRequest = const BasicProfile(0x00402017, "FillerOrderNumber_ImagingServiceRequest", Action.Z);
  static const kFrameComments = const BasicProfile(0x00209158, "FrameComments", Action.X);
  static const kFrameofReferenceUID = const BasicProfile(0x00200052, "FrameofReferenceUID", Action.U);
  static const kGantryID = const BasicProfile(0x00181008, "GantryID", Action.X);
  static const kGeneratorID = const BasicProfile(0x00181005, "GeneratorID", Action.X);
  static const kGraphicAnnotationSequence = const BasicProfile(0x00700001, "GraphicAnnotationSequence", Action.D);
  static const kHumanPerformersName = const BasicProfile(0x00404037, "HumanPerformersName", Action.X);
  static const kHumanPerformersOrganization = const BasicProfile(0x00404036, "HumanPerformersOrganization", Action.X);
  static const kIconImageSequence0xseeNote12 = const BasicProfile(0x00880200, "IconImageSequence0xseeNote12", Action.X);
  static const kIdentifyingComments = const BasicProfile(0x00084000, "IdentifyingComments", Action.X);
  static const kImageComments = const BasicProfile(0x00204000, "ImageComments", Action.X);
  static const kImagePresentationComments = const BasicProfile(0x00284000, "ImagePresentationComments", Action.X);
  static const kImagingServiceRequestComments = const BasicProfile(0x00402400, "ImagingServiceRequestComments", Action.X);
  static const kImpressions = const BasicProfile(0x40080300, "Impressions", Action.X);
  static const kInstanceCreatorUID = const BasicProfile(0x00080014, "InstanceCreatorUID", Action.U);
  static const kInstitutionAddress = const BasicProfile(0x00080081, "InstitutionAddress", Action.X);
  static const kInstitutionCodeSequence = const BasicProfile(0x00080082, "InstitutionCodeSequence", Action.XZD);
  static const kInstitutionName = const BasicProfile(0x00080080, "InstitutionName", Action.XZD);
  static const kInstitutionalDepartmentName = const BasicProfile(0x00081040, "InstitutionalDepartmentName", Action.X);
  static const kInsurancePlanIdentification = const BasicProfile(0x00101050, "InsurancePlanIdentification", Action.X);
  static const kIntendedRecipientsofResultsIdentificationSequence = const BasicProfile(0x00401011, "IntendedRecipientsofResultsIdentificationSequence", Action.X);
  static const kInterpretationApproverSequence = const BasicProfile(0x40080111, "InterpretationApproverSequence", Action.X);
  static const kInterpretationAuthor = const BasicProfile(0x4008010C, "InterpretationAuthor", Action.X);
  static const kInterpretationDiagnosisDescription = const BasicProfile(0x40080115, "InterpretationDiagnosisDescription", Action.X);
  static const kInterpretationIDIssuer = const BasicProfile(0x40080202, "InterpretationIDIssuer", Action.X);
  static const kInterpretationRecorder = const BasicProfile(0x40080102, "InterpretationRecorder", Action.X);
  static const kInterpretationText = const BasicProfile(0x4008010B, "InterpretationText", Action.X);
  static const kInterpretationTranscriber = const BasicProfile(0x4008010A, "InterpretationTranscriber", Action.X);
  static const kIrradiationEventUID = const BasicProfile(0x00083010, "IrradiationEventUID", Action.U);
  static const kIssuerofAdmissionID = const BasicProfile(0x00380011, "IssuerofAdmissionID", Action.X);
  static const kIssuerofPatientID = const BasicProfile(0x00100021, "IssuerofPatientID", Action.X);
  static const kIssuerofServiceEpisodeID = const BasicProfile(0x00380061, "IssuerofServiceEpisodeID", Action.X);
  static const kLargePaletteColorLookupTableUID = const BasicProfile(0x00281214, "LargePaletteColorLookupTableUID", Action.U);
  static const kLastMenstrualDate = const BasicProfile(0x001021D0, "LastMenstrualDate", Action.X);
  static const kMAC = const BasicProfile(0x04000404, "MAC", Action.X);
  static const kMediaStorageSOPInstanceUID = const BasicProfile(0x00020003, "MediaStorageSOPInstanceUID", Action.U);
  static const kMedicalAlerts = const BasicProfile(0x00102000, "MedicalAlerts", Action.X);
  static const kMedicalRecordLocator = const BasicProfile(0x00101090, "MedicalRecordLocator", Action.X);
  static const kMilitaryRank = const BasicProfile(0x00101080, "MilitaryRank", Action.X);
  static const kModifiedAttributesSequence = const BasicProfile(0x04000550, "ModifiedAttributesSequence", Action.X);
  static const kModifiedImageDescription = const BasicProfile(0x00203406, "ModifiedImageDescription", Action.X);
  static const kModifyingDeviceID = const BasicProfile(0x00203401, "ModifyingDeviceID", Action.X);
  static const kModifyingDeviceManufacturer = const BasicProfile(0x00203404, "ModifyingDeviceManufacturer", Action.X);
  static const kNameofPhysician0xsReadingStudy = const BasicProfile(0x00081060, "NameofPhysician0xsReadingStudy", Action.X);
  static const kNamesofIntendedRecipientofResults = const BasicProfile(0x00401010, "NamesofIntendedRecipientofResults", Action.X);
  static const kOccupation = const BasicProfile(0x00102180, "Occupation", Action.X);
  static const kOperatorsIdentificationSequence = const BasicProfile(0x00081072, "OperatorsIdentificationSequence", Action.XD);
  static const kOperatorsName = const BasicProfile(0x00081070, "OperatorsName", Action.XZD);
  static const kOriginalAttributesSequence = const BasicProfile(0x04000561, "OriginalAttributesSequence", Action.X);
  static const kOrderCallbackPhoneNumber = const BasicProfile(0x00402010, "OrderCallbackPhoneNumber", Action.X);
  static const kOrderEnteredBy = const BasicProfile(0x00402008, "OrderEnteredBy", Action.X);
  static const kOrderEntererLocation = const BasicProfile(0x00402009, "OrderEntererLocation", Action.X);
  static const kOtherPatientIDs = const BasicProfile(0x00101000, "OtherPatientIDs", Action.X);
  static const kOtherPatientIDsSequence = const BasicProfile(0x00101002, "OtherPatientIDsSequence", Action.X);
  static const kOtherPatientNames = const BasicProfile(0x00101001, "OtherPatientNames", Action.X);
  static const kOverlayComments = const BasicProfile(0x60004000, "OverlayComments", Action.X);
  static const kOverlayData = const BasicProfile(0x60003000, "OverlayData", Action.X);
  static const kOverlayDate = const BasicProfile(0x00080024, "OverlayDate", Action.X);
  static const kOverlayTime = const BasicProfile(0x00080034, "OverlayTime", Action.X);
  static const kPaletteColorLookupTableUID = const BasicProfile(0x00281199, "PaletteColorLookupTableUID", Action.U);
  static const kParticipantSequence = const BasicProfile(0x0040A07A, "ParticipantSequence", Action.X);
  static const kPatientAddress = const BasicProfile(0x00101040, "PatientAddress", Action.X);
  static const kPatientComments = const BasicProfile(0x00104000, "PatientComments", Action.X);
  static const kPatientID = const BasicProfile(0x00100020, "PatientID", Action.Z);
  static const kPatientSexNeutered = const BasicProfile(0x00102203, "PatientSexNeutered", Action.XZ);
  static const kPatientState = const BasicProfile(0x00380500, "PatientState", Action.X);
  static const kPatientTransportArrangements = const BasicProfile(0x00401004, "PatientTransportArrangements", Action.X);
  static const kPatientsAge = const BasicProfile(0x00101010, "PatientsAge", Action.X);
  static const kPatientsBirthDate = const BasicProfile(0x00100030, "PatientsBirthDate", Action.Z);
  static const kPatientsBirthName = const BasicProfile(0x00101005, "PatientsBirthName", Action.X);
  static const kPatientsBirthTime = const BasicProfile(0x00100032, "PatientsBirthTime", Action.X);
  static const kPatientsInstitutionResidence = const BasicProfile(0x00380400, "PatientsInstitutionResidence", Action.X);
  static const kPatientsInsurancePlanCodeSequence = const BasicProfile(0x00100050, "PatientsInsurancePlanCodeSequence", Action.X);
  static const kPatientsMothersBirthName = const BasicProfile(0x00101060, "PatientsMothersBirthName", Action.X);
  static const kPatientsName = const BasicProfile(0x00100010, "PatientsName", Action.Z);
  static const kPatientsPrimaryLanguageCodeSequence = const BasicProfile(0x00100101, "PatientsPrimaryLanguageCodeSequence", Action.X);
  static const kPatientsPrimaryLanguageModifierCodeSequence = const BasicProfile(0x00100102, "PatientsPrimaryLanguageModifierCodeSequence", Action.X);
  static const kPatientsReligiousPreference = const BasicProfile(0x001021F0, "PatientsReligiousPreference", Action.X);
  static const kPatientsSex = const BasicProfile(0x00100040, "PatientsSex", Action.Z);
  static const kPatientsSize = const BasicProfile(0x00101020, "PatientsSize", Action.X);
  static const kPatientsTelephoneNumbers = const BasicProfile(0x00102154, "PatientsTelephoneNumbers", Action.X);
  static const kPatientsWeight = const BasicProfile(0x00101030, "PatientsWeight", Action.X);
  static const kPerformedLocation = const BasicProfile(0x00400243, "PerformedLocation", Action.X);
  static const kPerformedProcedureStepDescription = const BasicProfile(0x00400254, "PerformedProcedureStepDescription", Action.X);
  static const kPerformedProcedureStepEndDate = const BasicProfile(0x00400250, "PerformedProcedureStepEndDate", Action.X);
  static const kPerformedProcedureStepEndTime = const BasicProfile(0x00400251, "PerformedProcedureStepEndTime", Action.X);
  static const kPerformedProcedureStepID = const BasicProfile(0x00400253, "PerformedProcedureStepID", Action.X);
  static const kPerformedProcedureStepStartDate = const BasicProfile(0x00400244, "PerformedProcedureStepStartDate", Action.X);
  static const kPerformedProcedureStepStartTime = const BasicProfile(0x00400245, "PerformedProcedureStepStartTime", Action.X);
  static const kPerformedStationAETitle = const BasicProfile(0x00400241, "PerformedStationAETitle", Action.X);
  static const kPerformedStationGeographicLocationCodeSequence = const BasicProfile(0x00404030, "PerformedStationGeographicLocationCodeSequence", Action.X);
  static const kPerformedStationName = const BasicProfile(0x00400242, "PerformedStationName", Action.X);
  static const kPerformedStationNameCodeSequence = const BasicProfile(0x00404028, "PerformedStationNameCodeSequence", Action.X);
  static const kPerformingPhysicianIdentificationSequence = const BasicProfile(0x00081052, "PerformingPhysicianIdentificationSequence", Action.X);
  static const kPerformingPhysiciansName = const BasicProfile(0x00081050, "PerformingPhysiciansName", Action.X);
  static const kPersonAddress = const BasicProfile(0x00401102, "PersonAddress", Action.X);
  static const kPersonIdentificationCodeSequence = const BasicProfile(0x00401101, "PersonIdentificationCodeSequence", Action.D);
  static const kPersonName = const BasicProfile(0x0040A123, "PersonName", Action.D);
  static const kPersonTelephoneNumbers = const BasicProfile(0x00401103, "PersonTelephoneNumbers", Action.X);
  static const kPhysicianApprovingInterpretation = const BasicProfile(0x40080114, "PhysicianApprovingInterpretation", Action.X);
  static const kPhysician0xsReadingStudyIdentificationSequence = const BasicProfile(0x00081062, "Physician0xsReadingStudyIdentificationSequence", Action.X);
  static const kPhysician0xsofRecord = const BasicProfile(0x00081048, "Physician0xsofRecord", Action.X);
  static const kPhysician0xsofRecordIdentificationSequence = const BasicProfile(0x00081049, "Physician0xsofRecordIdentificationSequence", Action.X);
  static const kPlacerOrderNumber_ImagingServiceRequest = const BasicProfile(0x00402016, "PlacerOrderNumber_ImagingServiceRequest", Action.Z);
  static const kPlateID = const BasicProfile(0x00181004, "PlateID", Action.X);
  static const kPre_Medication = const BasicProfile(0x00400012, "Pre_Medication", Action.X);
  static const kPregnancyStatus = const BasicProfile(0x001021C0, "PregnancyStatus", Action.X);
  static const kProtocolName = const BasicProfile(0x00181030, "ProtocolName", Action.XD);
  static const kReasonfortheImagingServiceRequest = const BasicProfile(0x00402001, "ReasonfortheImagingServiceRequest", Action.X);
  static const kReasonforStudy = const BasicProfile(0x00321030, "ReasonforStudy", Action.X);
  static const kReferencedDigitalSignatureSequence = const BasicProfile(0x04000402, "ReferencedDigitalSignatureSequence", Action.X);
  static const kReferencedFrameofReferenceUID = const BasicProfile(0x30060024, "ReferencedFrameofReferenceUID", Action.U);
  static const kReferencedGeneralPurposeScheduledProcedureStepTransactionUID = const BasicProfile(0x00404023, "ReferencedGeneralPurposeScheduledProcedureStepTransactionUID", Action.U);
  static const kReferencedImageSequence = const BasicProfile(0x00081140, "ReferencedImageSequence", Action.XZU);
  static const kReferencedPatientAliasSequence = const BasicProfile(0x00380004, "ReferencedPatientAliasSequence", Action.X);
  static const kReferencedPatientSequence = const BasicProfile(0x00081120, "ReferencedPatientSequence", Action.X);
  static const kReferencedPerformedProcedureStepSequence = const BasicProfile(0x00081111, "ReferencedPerformedProcedureStepSequence", Action.XZD);
  static const kReferencedSOPInstanceMACSequence = const BasicProfile(0x04000403, "ReferencedSOPInstanceMACSequence", Action.X);
  static const kReferencedSOPInstanceUID = const BasicProfile(0x00081155, "ReferencedSOPInstanceUID", Action.U);
  static const kReferencedSOPInstanceUIDinFile = const BasicProfile(0x00041511, "ReferencedSOPInstanceUIDinFile", Action.U);
  static const kReferencedStudySequence = const BasicProfile(0x00081110, "ReferencedStudySequence", Action.XZ);
  static const kReferringPhysiciansAddress = const BasicProfile(0x00080092, "ReferringPhysiciansAddress", Action.X);
  static const kReferringPhysiciansIdentificationSequence = const BasicProfile(0x00080096, "ReferringPhysiciansIdentificationSequence", Action.X);
  static const kReferringPhysiciansName = const BasicProfile(0x00080090, "ReferringPhysiciansName", Action.Z);
  static const kReferringPhysiciansTelephoneNumbers = const BasicProfile(0x00080094, "ReferringPhysiciansTelephoneNumbers", Action.X);
  static const kRegionofResidence = const BasicProfile(0x00102152, "RegionofResidence", Action.X);
  static const kRelatedFrameofReferenceUID = const BasicProfile(0x300600C2, "RelatedFrameofReferenceUID", Action.U);
  static const kRequestAttributesSequence = const BasicProfile(0x00400275, "RequestAttributesSequence", Action.X);
  static const kRequestedContrastAgent = const BasicProfile(0x00321070, "RequestedContrastAgent", Action.X);
  static const kRequestedProcedureComments = const BasicProfile(0x00401400, "RequestedProcedureComments", Action.X);
  static const kRequestedProcedureDescription = const BasicProfile(0x00321060, "RequestedProcedureDescription", Action.XZ);
  static const kRequestedProcedureID = const BasicProfile(0x00401001, "RequestedProcedureID", Action.X);
  static const kRequestedProcedureLocation = const BasicProfile(0x00401005, "RequestedProcedureLocation", Action.X);
  static const kRequestedSOPInstanceUID = const BasicProfile(0x00001001, "RequestedSOPInstanceUID", Action.U);
  static const kRequestingPhysician = const BasicProfile(0x00321032, "RequestingPhysician", Action.X);
  static const kRequestingService = const BasicProfile(0x00321033, "RequestingService", Action.X);
  static const kResponsibleOrganization = const BasicProfile(0x00102299, "ResponsibleOrganization", Action.X);
  static const kResponsiblePerson = const BasicProfile(0x00102297, "ResponsiblePerson", Action.X);
  static const kResultsComments = const BasicProfile(0x40084000, "ResultsComments", Action.X);
  static const kResultsDistributionListSequence = const BasicProfile(0x40080118, "ResultsDistributionListSequence", Action.X);
  static const kResultsIDIssuer = const BasicProfile(0x40080042, "ResultsIDIssuer", Action.X);
  static const kReviewerName = const BasicProfile(0x300E0008, "ReviewerName", Action.XZ);
  static const kScheduledHumanPerformersSequence = const BasicProfile(0x00404034, "ScheduledHumanPerformersSequence", Action.X);
  static const kScheduledPatientInstitutionResidence = const BasicProfile(0x0038001E, "ScheduledPatientInstitutionResidence", Action.X);
  static const kScheduledPerformingPhysicianIdentificationSequence = const BasicProfile(0x0040000B, "ScheduledPerformingPhysicianIdentificationSequence", Action.X);
  static const kScheduledPerformingPhysicianName = const BasicProfile(0x00400006, "ScheduledPerformingPhysicianName", Action.X);
  static const kScheduledProcedureStepEndDate = const BasicProfile(0x00400004, "ScheduledProcedureStepEndDate", Action.X);
  static const kScheduledProcedureStepEndTime = const BasicProfile(0x00400005, "ScheduledProcedureStepEndTime", Action.X);
  static const kScheduledProcedureStepDescription = const BasicProfile(0x00400007, "ScheduledProcedureStepDescription", Action.X);
  static const kScheduledProcedureStepLocation = const BasicProfile(0x00400011, "ScheduledProcedureStepLocation", Action.X);
  static const kScheduledProcedureStepStartDate = const BasicProfile(0x00400002, "ScheduledProcedureStepStartDate", Action.X);
  static const kScheduledProcedureStepStartTime = const BasicProfile(0x00400003, "ScheduledProcedureStepStartTime", Action.X);
  static const kScheduledStationAETitle = const BasicProfile(0x00400001, "ScheduledStationAETitle", Action.X);
  static const kScheduledStationGeographicLocationCodeSequence = const BasicProfile(0x00404027, "ScheduledStationGeographicLocationCodeSequence", Action.X);
  static const kScheduledStationName = const BasicProfile(0x00400010, "ScheduledStationName", Action.X);
  static const kScheduledStationNameCodeSequence = const BasicProfile(0x00404025, "ScheduledStationNameCodeSequence", Action.X);
  static const kScheduledStudyLocation = const BasicProfile(0x00321020, "ScheduledStudyLocation", Action.X);
  static const kScheduledStudyLocationAETitle = const BasicProfile(0x00321021, "ScheduledStudyLocationAETitle", Action.X);
  static const kSeriesDate = const BasicProfile(0x00080021, "SeriesDate", Action.XD);
  static const kSeriesDescription = const BasicProfile(0x0008103E, "SeriesDescription", Action.X);
  static const kSeriesInstanceUID = const BasicProfile(0x0020000E, "SeriesInstanceUID", Action.U);
  static const kSeriesTime = const BasicProfile(0x00080031, "SeriesTime", Action.XD);
  static const kServiceEpisodeDescription = const BasicProfile(0x00380062, "ServiceEpisodeDescription", Action.X);
  static const kServiceEpisodeID = const BasicProfile(0x00380060, "ServiceEpisodeID", Action.X);
  static const kSmokingStatus = const BasicProfile(0x001021A0, "SmokingStatus", Action.X);
  static const kSOPInstanceUID = const BasicProfile(0x00080018, "SOPInstanceUID", Action.U);
  static const kSourceImageSequence = const BasicProfile(0x00082112, "SourceImageSequence", Action.XZU);
  static const kSpecialNeeds = const BasicProfile(0x00380050, "SpecialNeeds", Action.X);
  static const kStationName = const BasicProfile(0x00081010, "StationName", Action.XZD);
  static const kStorageMediaFile_setUID = const BasicProfile(0x00880140, "StorageMediaFile_setUID", Action.U);
  static const kStudyComments = const BasicProfile(0x00324000, "StudyComments", Action.X);
  static const kStudyDate = const BasicProfile(0x00080020, "StudyDate", Action.Z);
  static const kStudyDescription = const BasicProfile(0x00081030, "StudyDescription", Action.X);
  static const kStudyID = const BasicProfile(0x00200010, "StudyID", Action.Z);
  static const kStudyIDIssuer = const BasicProfile(0x00320012, "StudyIDIssuer", Action.X);
  static const kStudyInstanceUID = const BasicProfile(0x0020000D, "StudyInstanceUID", Action.U);
  static const kStudyTime = const BasicProfile(0x00080030, "StudyTime", Action.Z);
  static const kSynchronizationFrameofReferenceUID = const BasicProfile(0x00200200, "SynchronizationFrameofReferenceUID", Action.U);
  static const kTemplateExtensionCreatorUID = const BasicProfile(0x0040DB0D, "TemplateExtensionCreatorUID", Action.U);
  static const kTemplateExtensionOrganizationUID = const BasicProfile(0x0040DB0C, "TemplateExtensionOrganizationUID", Action.U);
  static const kTextComments = const BasicProfile(0x40004000, "TextComments", Action.X);
  static const kTextString = const BasicProfile(0x20300020, "TextString", Action.X);
  static const kTimezoneOffsetFromUTC = const BasicProfile(0x00080201, "TimezoneOffsetFromUTC", Action.X);
  static const kTopicAuthor = const BasicProfile(0x00880910, "TopicAuthor", Action.X);
  static const kTopicKeywords = const BasicProfile(0x00880912, "TopicKeywords", Action.X);
  static const kTopicSubject = const BasicProfile(0x00880906, "TopicSubject", Action.X);
  static const kTopicTitle = const BasicProfile(0x00880904, "TopicTitle", Action.X);
  static const kTransactionUID = const BasicProfile(0x00081195, "TransactionUID", Action.U);
  static const kUID = const BasicProfile(0x0040A124, "UID", Action.U);
  static const kVerifyingObserverIdentificationCodeSequence = const BasicProfile(0x0040A088, "VerifyingObserverIdentificationCodeSequence", Action.Z);
  static const kVerifyingObserverName = const BasicProfile(0x0040A075, "VerifyingObserverName", Action.D);
  static const kVerifyingObserverSequence = const BasicProfile(0x0040A073, "VerifyingObserverSequence", Action.D);
  static const kVerifyingOrganization = const BasicProfile(0x0040A027, "VerifyingOrganization", Action.X);
  static const kVisitComments = const BasicProfile(0x00384000, "VisitComments", Action.X);


  static const Map<int, BasicProfile> tagToBasicProfile = const {
    0x00080050: kAccessionNumber,
    0x00184000: kAcquisitionComments,
    0x00400555: kAcquisitionContextSequence,
    0x00080022: kAcquisitionDate,
    0x0008002A: kAcquisitionDateTime,
    0x00181400: kAcquisitionDeviceProcessingDescription,
    0x00189424: kAcquisitionProtocolDescription,
    0x00080032: kAcquisitionTime,
    0x00404035: kActualHumanPerformersSequence,
    0x001021B0: kAdditionalPatientsHistory,
    0x00380010: kAdmissionID,
    0x00380020: kAdmittingDate,
    0x00081084: kAdmittingDiagnosesCodeSequence,
    0x00081080: kAdmittingDiagnosesDescription,
    0x00380021: kAdmittingTime,
    0x00001000: kAffectedSOPInstanceUID,
    0x00102110: kAllergies,
    0x40000010: kArbitrary,
    0x0040A078: kAuthorObserverSequence,
    0x00101081: kBranchofService,
    0x00181007: kCassetteID,
    0x00400280: kCommentsonthePerformedProcedureStep,
    0x00209161: kConcatenationUID,
    0x00403001: kConfidentialityConstraintonPatientDataDescription,
    0x00700084: kContentCreatorsName,
    0x00700086: kContentCreatorsIdentificationCodeSequence,
    0x00080023: kContentDate,
    0x0040A730: kContentSequence,
    0x00080033: kContentTime,
    0x0008010D: kContextGroupExtensionCreatorUID,
    0x00180010: kContrastBolusAgent,
    0x0018A003: kContributionDescription,
    0x00102150: kCountryofResidence,
    0x00089123: kCreatorVersionUID,
    0x00380300: kCurrentPatientLocation,
   // 0x50xxxxxx: kCurveData,
    0x00080025: kCurveDate,
    0x00080035: kCurveTime,
    0x0040A07C: kCustodialOrganizationSequence,
    0xFFFCFFFC: kDataSetTrailingPadding,
    0x00082111: kDerivationDescription,
    0x0018700A: kDetectorID,
    0x00181000: kDeviceSerialNumber,
    0x00181002: kDeviceUID,
    0x04000100: kDigitalSignatureUID,
    0xFFFAFFFA: kDigitalSignaturesSequence,
    0x00209164: kDimensionOrganizationUID,
    0x00380040: kDischargeDiagnosisDescription,
    0x4008011A: kDistributionAddress,
    0x40080119: kDistributionName,
    0x300A0013: kDoseReferenceUID,
    0x00102160: kEthnicGroup,
    0x00080058: kFailedSOPInstanceUIDList,
    0x0070031A: kFiducialUID,
    0x00402017: kFillerOrderNumber_ImagingServiceRequest,
    0x00209158: kFrameComments,
    0x00200052: kFrameofReferenceUID,
    0x00181008: kGantryID,
    0x00181005: kGeneratorID,
    0x00700001: kGraphicAnnotationSequence,
    0x00404037: kHumanPerformersName,
    0x00404036: kHumanPerformersOrganization,
    0x00880200: kIconImageSequence0xseeNote12,
    0x00084000: kIdentifyingComments,
    0x00204000: kImageComments,
    0x00284000: kImagePresentationComments,
    0x00402400: kImagingServiceRequestComments,
    0x40080300: kImpressions,
    0x00080014: kInstanceCreatorUID,
    0x00080081: kInstitutionAddress,
    0x00080082: kInstitutionCodeSequence,
    0x00080080: kInstitutionName,
    0x00081040: kInstitutionalDepartmentName,
    0x00101050: kInsurancePlanIdentification,
    0x00401011: kIntendedRecipientsofResultsIdentificationSequence,
    0x40080111: kInterpretationApproverSequence,
    0x4008010C: kInterpretationAuthor,
    0x40080115: kInterpretationDiagnosisDescription,
    0x40080202: kInterpretationIDIssuer,
    0x40080102: kInterpretationRecorder,
    0x4008010B: kInterpretationText,
    0x4008010A: kInterpretationTranscriber,
    0x00083010: kIrradiationEventUID,
    0x00380011: kIssuerofAdmissionID,
    0x00100021: kIssuerofPatientID,
    0x00380061: kIssuerofServiceEpisodeID,
    0x00281214: kLargePaletteColorLookupTableUID,
    0x001021D0: kLastMenstrualDate,
    0x04000404: kMAC,
    0x00020003: kMediaStorageSOPInstanceUID,
    0x00102000: kMedicalAlerts,
    0x00101090: kMedicalRecordLocator,
    0x00101080: kMilitaryRank,
    0x04000550: kModifiedAttributesSequence,
    0x00203406: kModifiedImageDescription,
    0x00203401: kModifyingDeviceID,
    0x00203404: kModifyingDeviceManufacturer,
    0x00081060: kNameofPhysician0xsReadingStudy,
    0x00401010: kNamesofIntendedRecipientofResults,
    0x00102180: kOccupation,
    0x00081072: kOperatorsIdentificationSequence,
    0x00081070: kOperatorsName,
    0x04000561: kOriginalAttributesSequence,
    0x00402010: kOrderCallbackPhoneNumber,
    0x00402008: kOrderEnteredBy,
    0x00402009: kOrderEntererLocation,
    0x00101000: kOtherPatientIDs,
    0x00101002: kOtherPatientIDsSequence,
    0x00101001: kOtherPatientNames,
    //0x60xx4000: kOverlayComments,
    //0x60xx3000: kOverlayData,
    0x00080024: kOverlayDate,
    0x00080034: kOverlayTime,
    0x00281199: kPaletteColorLookupTableUID,
    0x0040A07A: kParticipantSequence,
    0x00101040: kPatientAddress,
    0x00104000: kPatientComments,
    0x00100020: kPatientID,
    0x00102203: kPatientSexNeutered,
    0x00380500: kPatientState,
    0x00401004: kPatientTransportArrangements,
    0x00101010: kPatientsAge,
    0x00100030: kPatientsBirthDate,
    0x00101005: kPatientsBirthName,
    0x00100032: kPatientsBirthTime,
    0x00380400: kPatientsInstitutionResidence,
    0x00100050: kPatientsInsurancePlanCodeSequence,
    0x00101060: kPatientsMothersBirthName,
    0x00100010: kPatientsName,
    0x00100101: kPatientsPrimaryLanguageCodeSequence,
    0x00100102: kPatientsPrimaryLanguageModifierCodeSequence,
    0x001021F0: kPatientsReligiousPreference,
    0x00100040: kPatientsSex,
    0x00101020: kPatientsSize,
    0x00102154: kPatientsTelephoneNumbers,
    0x00101030: kPatientsWeight,
    0x00400243: kPerformedLocation,
    0x00400254: kPerformedProcedureStepDescription,
    0x00400250: kPerformedProcedureStepEndDate,
    0x00400251: kPerformedProcedureStepEndTime,
    0x00400253: kPerformedProcedureStepID,
    0x00400244: kPerformedProcedureStepStartDate,
    0x00400245: kPerformedProcedureStepStartTime,
    0x00400241: kPerformedStationAETitle,
    0x00404030: kPerformedStationGeographicLocationCodeSequence,
    0x00400242: kPerformedStationName,
    0x00404028: kPerformedStationNameCodeSequence,
    0x00081052: kPerformingPhysicianIdentificationSequence,
    0x00081050: kPerformingPhysiciansName,
    0x00401102: kPersonAddress,
    0x00401101: kPersonIdentificationCodeSequence,
    0x0040A123: kPersonName,
    0x00401103: kPersonTelephoneNumbers,
    0x40080114: kPhysicianApprovingInterpretation,
    0x00081062: kPhysician0xsReadingStudyIdentificationSequence,
    0x00081048: kPhysician0xsofRecord,
    0x00081049: kPhysician0xsofRecordIdentificationSequence,
    0x00402016: kPlacerOrderNumber_ImagingServiceRequest,
    0x00181004: kPlateID,
    0x00400012: kPre_Medication,
    0x001021C0: kPregnancyStatus,
    0x00181030: kProtocolName,
    0x00402001: kReasonfortheImagingServiceRequest,
    0x00321030: kReasonforStudy,
    0x04000402: kReferencedDigitalSignatureSequence,
    0x30060024: kReferencedFrameofReferenceUID,
    0x00404023: kReferencedGeneralPurposeScheduledProcedureStepTransactionUID,
    0x00081140: kReferencedImageSequence,
    0x00380004: kReferencedPatientAliasSequence,
    0x00081120: kReferencedPatientSequence,
    0x00081111: kReferencedPerformedProcedureStepSequence,
    0x04000403: kReferencedSOPInstanceMACSequence,
    0x00081155: kReferencedSOPInstanceUID,
    0x00041511: kReferencedSOPInstanceUIDinFile,
    0x00081110: kReferencedStudySequence,
    0x00080092: kReferringPhysiciansAddress,
    0x00080096: kReferringPhysiciansIdentificationSequence,
    0x00080090: kReferringPhysiciansName,
    0x00080094: kReferringPhysiciansTelephoneNumbers,
    0x00102152: kRegionofResidence,
    0x300600C2: kRelatedFrameofReferenceUID,
    0x00400275: kRequestAttributesSequence,
    0x00321070: kRequestedContrastAgent,
    0x00401400: kRequestedProcedureComments,
    0x00321060: kRequestedProcedureDescription,
    0x00401001: kRequestedProcedureID,
    0x00401005: kRequestedProcedureLocation,
    0x00001001: kRequestedSOPInstanceUID,
    0x00321032: kRequestingPhysician,
    0x00321033: kRequestingService,
    0x00102299: kResponsibleOrganization,
    0x00102297: kResponsiblePerson,
    0x40084000: kResultsComments,
    0x40080118: kResultsDistributionListSequence,
    0x40080042: kResultsIDIssuer,
    0x300E0008: kReviewerName,
    0x00404034: kScheduledHumanPerformersSequence,
    0x0038001E: kScheduledPatientInstitutionResidence,
    0x0040000B: kScheduledPerformingPhysicianIdentificationSequence,
    0x00400006: kScheduledPerformingPhysicianName,
    0x00400004: kScheduledProcedureStepEndDate,
    0x00400005: kScheduledProcedureStepEndTime,
    0x00400007: kScheduledProcedureStepDescription,
    0x00400011: kScheduledProcedureStepLocation,
    0x00400002: kScheduledProcedureStepStartDate,
    0x00400003: kScheduledProcedureStepStartTime,
    0x00400001: kScheduledStationAETitle,
    0x00404027: kScheduledStationGeographicLocationCodeSequence,
    0x00400010: kScheduledStationName,
    0x00404025: kScheduledStationNameCodeSequence,
    0x00321020: kScheduledStudyLocation,
    0x00321021: kScheduledStudyLocationAETitle,
    0x00080021: kSeriesDate,
    0x0008103E: kSeriesDescription,
    0x0020000E: kSeriesInstanceUID,
    0x00080031: kSeriesTime,
    0x00380062: kServiceEpisodeDescription,
    0x00380060: kServiceEpisodeID,
    0x001021A0: kSmokingStatus,
    0x00080018: kSOPInstanceUID,
    0x00082112: kSourceImageSequence,
    0x00380050: kSpecialNeeds,
    0x00081010: kStationName,
    0x00880140: kStorageMediaFile_setUID,
    0x00324000: kStudyComments,
    0x00080020: kStudyDate,
    0x00081030: kStudyDescription,
    0x00200010: kStudyID,
    0x00320012: kStudyIDIssuer,
    0x0020000D: kStudyInstanceUID,
    0x00080030: kStudyTime,
    0x00200200: kSynchronizationFrameofReferenceUID,
    0x0040DB0D: kTemplateExtensionCreatorUID,
    0x0040DB0C: kTemplateExtensionOrganizationUID,
    0x40004000: kTextComments,
    0x20300020: kTextString,
    0x00080201: kTimezoneOffsetFromUTC,
    0x00880910: kTopicAuthor,
    0x00880912: kTopicKeywords,
    0x00880906: kTopicSubject,
    0x00880904: kTopicTitle,
    0x00081195: kTransactionUID,
    0x0040A124: kUID,
    0x0040A088: kVerifyingObserverIdentificationCodeSequence,
    0x0040A075: kVerifyingObserverName,
    0x0040A073: kVerifyingObserverSequence,
    0x0040A027: kVerifyingOrganization,
    0x00384000: kVisitComments,
  };


}
  